import type { PanelLocale } from "@/lib/panel-i18n";

const copy = {
  lt: {
    noPdf: "PDF nepridėtas",
    openRecord: "Atidaryti įrašą",
    readOnly: "Pasirinktas įrašas · tik peržiūra",
    unavailable: "Pasirinktas įrašas šioje byloje nepasiekiamas.",
    invoice: "Sąskaitos įrašas",
    warranty: "Garantijos įrašas",
    status: "Būsena",
    work: "Darbas",
    created: "Sukurta",
    subtotal: "Suma be PVM",
    vat: "PVM",
    total: "Suma su PVM",
    issued: "Išrašyta",
    due: "Apmokėti iki",
    external: "Buhalterinės sistemos nuoroda",
    note: "Vidinė pastaba",
    scope: "Garantijos apimtis",
    starts: "Galioja nuo",
    ends: "Galioja iki",
    terms: "Sąlygų versija",
  },
  nb: {
    noPdf: "PDF ikke vedlagt",
    openRecord: "Åpne oppføring",
    readOnly: "Valgt oppføring · kun visning",
    unavailable: "Den valgte oppføringen er ikke tilgjengelig i denne saken.",
    invoice: "Fakturaoppføring",
    warranty: "Garantioppføring",
    status: "Status",
    work: "Oppdrag",
    created: "Opprettet",
    subtotal: "Beløp eks. mva.",
    vat: "Mva.",
    total: "Beløp inkl. mva.",
    issued: "Utstedt",
    due: "Forfallsdato",
    external: "Referanse i regnskapssystem",
    note: "Intern merknad",
    scope: "Garantiomfang",
    starts: "Gyldig fra",
    ends: "Gyldig til",
    terms: "Vilkårsversjon",
  },
  en: {
    noPdf: "PDF not attached",
    openRecord: "Open record",
    readOnly: "Selected record · read only",
    unavailable: "The selected record is not available in this case.",
    invoice: "Invoice record",
    warranty: "Warranty record",
    status: "Status",
    work: "Work order",
    created: "Created",
    subtotal: "Amount excluding VAT",
    vat: "VAT",
    total: "Amount including VAT",
    issued: "Issued",
    due: "Due",
    external: "Accounting system reference",
    note: "Internal note",
    scope: "Warranty scope",
    starts: "Valid from",
    ends: "Valid until",
    terms: "Terms version",
  },
};
export function getCaseRecordCopy(locale: PanelLocale) {
  return copy[locale];
}
