import type {
  AdminNextCapabilityState,
  AdminNextModuleId,
} from "@/lib/admin-next/rollout-view";
import type { PanelLocale } from "@/lib/panel-i18n";
import type { FeatureFlagName, IntegrationName } from "@/lib/platform/features";

export const platformHealthCopy = {
  nb: {
    title: "Systemstatus",
    intro:
      "Nåværende Preview-status og godkjenningene for produksjonslansering vises som to separate beslutninger.",
    previewEyebrow: "Nåværende miljø",
    previewTitle: "Preview-status nå",
    previewIntro:
      "Viser hvilke moduler som faktisk kan testes her, basert på aktiverte funksjoner, avhengigheter og driftssignaler.",
    previewReady: "Preview-modulene er klare for kontrollert testing",
    previewAttention: "Deler av Preview er fortsatt begrenset",
    previewOff: "Preview er ikke aktivert i dette miljøet",
    canonicalActive: "Admin Next er aktivert for full drift",
    availableModules: "Tilgjengelige moduler",
    moduleAttention: "Begrensede moduler",
    operationalSignals: "Driftssignaler",
    modules: "Modulstatus",
    integrations: "Integrasjoner og konfigurasjon",
    operations: "Drift og gjenoppretting",
    ready: "Klar",
    attention: "Må følges opp",
    disabled: "Deaktivert med vilje",
    productionEyebrow: "Separat lanseringsbeslutning",
    productionTitle: "Godkjenninger for produksjonslansering",
    productionIntro:
      "At Preview virker er ikke en produksjonsgodkjenning. Bare dokumenterte QA-, eier-, sikkerhets- og gjenopprettingskrav kan åpne denne porten.",
    productionReady: "Alle aktive produksjonskrav er godkjent",
    productionBlocked: "Produksjonslanseringen er fortsatt blokkert",
    go: "Godkjent",
    noGo: "Blokkert",
    blockers: "Aktive produksjonsblokkeringer",
    noBlockers: "Ingen aktive blokkeringer",
    requirements: "Det som mangler",
    requirementPending: "Påkrevd godkjenning er ikke dokumentert",
    technical: "Teknisk informasjon",
    technicalCodes: "Tekniske koder",
    featureFlag: "Funksjonsbryter",
    missingEvidence: "Manglende referanser",
    missingIntegrations: "Manglende integrasjoner",
    provider: "Leverandør",
    lastJob: "Siste fullførte bakgrunnsjobb",
    overdueJobs: "Forfalte bakgrunnsjobber",
    failedJobs: "Feilede bakgrunnsjobber",
    email: "Siste leverte e-post",
    emailFailures: "E-postfeil",
    seo: "Siste SEO-kjøring",
    seoFailures: "SEO-feil",
    quota: "Kapasitetsvarsler",
    backup: "Sist verifiserte sikkerhetskopi",
    missing: "Ikke registrert",
    evidence: "Gjenopprettingstest er dokumentert",
    noEvidence: "Gjenopprettingstest er ikke dokumentert",
    generated: "Status oppdatert",
  },
  lt: {
    title: "Sistemos būklė",
    intro:
      "Dabartinė Preview būklė ir Production paleidimo patvirtinimai rodomi kaip du atskiri sprendimai.",
    previewEyebrow: "Dabartinė aplinka",
    previewTitle: "Preview būklė dabar",
    previewIntro:
      "Rodoma, kuriuos modulius čia realiai galima tikrinti pagal įjungtas funkcijas, jų priklausomybes ir veikimo signalus.",
    previewReady: "Preview moduliai paruošti kontroliuojamam testavimui",
    previewAttention: "Dalis Preview dar ribojama",
    previewOff: "Preview šioje aplinkoje neįjungta",
    canonicalActive: "Admin Next įjungtas pilnam veikimui",
    availableModules: "Pasiekiami moduliai",
    moduleAttention: "Ribojami moduliai",
    operationalSignals: "Veikimo signalai",
    modules: "Modulių būsenos",
    integrations: "Integracijos ir konfigūracija",
    operations: "Veikimas ir atkūrimas",
    ready: "Paruošta",
    attention: "Reikia dėmesio",
    disabled: "Sąmoningai išjungta",
    productionEyebrow: "Atskiras paleidimo sprendimas",
    productionTitle: "Production paleidimo patvirtinimai",
    productionIntro:
      "Veikianti Preview nėra Production patvirtinimas. Šiuos vartus atveria tik užfiksuoti QA, savininko, saugumo ir atkūrimo reikalavimai.",
    productionReady: "Visi aktyvūs Production reikalavimai patvirtinti",
    productionBlocked: "Production paleidimas vis dar užblokuotas",
    go: "Patvirtinta",
    noGo: "Užblokuota",
    blockers: "Aktyvūs Production blokavimai",
    noBlockers: "Aktyvių blokavimų nėra",
    requirements: "Ko trūksta",
    requirementPending: "Privalomas patvirtinimas neužfiksuotas",
    technical: "Techninė informacija",
    technicalCodes: "Techniniai kodai",
    featureFlag: "Funkcijos jungiklis",
    missingEvidence: "Trūkstamos nuorodos",
    missingIntegrations: "Trūkstamos integracijos",
    provider: "Teikėjas",
    lastJob: "Paskutinė sėkminga foninė užduotis",
    overdueJobs: "Vėluojančios foninės užduotys",
    failedJobs: "Nepavykusios foninės užduotys",
    email: "Paskutinis pristatytas laiškas",
    emailFailures: "El. pašto klaidos",
    seo: "Paskutinis SEO vykdymas",
    seoFailures: "SEO klaidos",
    quota: "Pajėgumo perspėjimai",
    backup: "Paskutinė patikrinta atsarginė kopija",
    missing: "Neužfiksuota",
    evidence: "Atkūrimo bandymas dokumentuotas",
    noEvidence: "Atkūrimo bandymas nedokumentuotas",
    generated: "Būklė atnaujinta",
  },
  en: {
    title: "System health",
    intro:
      "Current Preview health and Production-release approvals are presented as two separate decisions.",
    previewEyebrow: "Current environment",
    previewTitle: "Preview health now",
    previewIntro:
      "Shows which modules can actually be tested here, based on enabled features, dependencies, and operational signals.",
    previewReady: "Preview modules are ready for controlled testing",
    previewAttention: "Parts of Preview remain limited",
    previewOff: "Preview is not enabled in this environment",
    canonicalActive: "Admin Next is enabled for full operation",
    availableModules: "Available modules",
    moduleAttention: "Limited modules",
    operationalSignals: "Operational signals",
    modules: "Module status",
    integrations: "Integrations and configuration",
    operations: "Operations and recovery",
    ready: "Ready",
    attention: "Needs attention",
    disabled: "Intentionally disabled",
    productionEyebrow: "Separate release decision",
    productionTitle: "Production-release approvals",
    productionIntro:
      "A working Preview is not Production approval. Only recorded QA, owner, security, and recovery requirements can open this gate.",
    productionReady: "All active Production requirements are approved",
    productionBlocked: "The Production release remains blocked",
    go: "Approved",
    noGo: "Blocked",
    blockers: "Active Production blockers",
    noBlockers: "No active blockers",
    requirements: "What is missing",
    requirementPending: "A required approval is not documented",
    technical: "Technical information",
    technicalCodes: "Technical codes",
    featureFlag: "Feature flag",
    missingEvidence: "Missing references",
    missingIntegrations: "Missing integrations",
    provider: "Provider",
    lastJob: "Last completed background job",
    overdueJobs: "Overdue background jobs",
    failedJobs: "Failed background jobs",
    email: "Last delivered email",
    emailFailures: "Email failures",
    seo: "Last SEO run",
    seoFailures: "SEO failures",
    quota: "Capacity warnings",
    backup: "Last verified backup",
    missing: "Not recorded",
    evidence: "Recovery test is documented",
    noEvidence: "Recovery test is not documented",
    generated: "Status updated",
  },
} as const;

export const moduleLabels: Record<
  PanelLocale,
  Record<AdminNextModuleId, string>
> = {
  nb: {
    today: "Dagens arbeidskø",
    caseWorkspace: "Saksarbeidsflate",
    roofWorkbench: "Takmåling og R4",
    documentPreflight: "Dokumentpakke og forhåndskontroll",
    fieldVisit: "Medarbeiderbesøk",
  },
  lt: {
    today: "Šiandienos darbų eilė",
    caseWorkspace: "Bylos darbo erdvė",
    roofWorkbench: "Stogo matavimas ir R4",
    documentPreflight: "Dokumentų paketas ir išankstinė patikra",
    fieldVisit: "Darbuotojo vizitas",
  },
  en: {
    today: "Today's work queue",
    caseWorkspace: "Case workspace",
    roofWorkbench: "Roof measurement and R4",
    documentPreflight: "Document package and preflight",
    fieldVisit: "Worker visit",
  },
};

export const featureLabels: Record<
  PanelLocale,
  Record<FeatureFlagName, string>
> = {
  nb: {
    aiDrafts: "KI-utkast",
    roofMeasurement: "Takmåling",
    roofFusionV1: "Roof Fusion",
    customerQuotes: "Kundetilbud",
    contractSigning: "Kontraktsignering",
    workerPortal: "Medarbeiderportal",
    automatedReminders: "Automatiske påminnelser",
    seoScheduler: "Planlagt SEO-arbeid",
    caseStateEngineV2: "Saksflyt",
    measurementEvidenceV2: "Målegrunnlag",
    adminExceptionFlowsV2: "Avvikshåndtering",
    communicationRoutingV2: "Kommunikasjonsflyt",
    customerLifecycleV2: "Kundereise",
    securityHardeningV2: "Sikkerhetsforsterkning",
  },
  lt: {
    aiDrafts: "DI juodraščiai",
    roofMeasurement: "Stogo matavimas",
    roofFusionV1: "Roof Fusion",
    customerQuotes: "Pasiūlymai klientams",
    contractSigning: "Sutarčių pasirašymas",
    workerPortal: "Darbuotojo portalas",
    automatedReminders: "Automatiniai priminimai",
    seoScheduler: "Planinis SEO vykdymas",
    caseStateEngineV2: "Bylos eiga",
    measurementEvidenceV2: "Matavimo įrodymai",
    adminExceptionFlowsV2: "Išimčių valdymas",
    communicationRoutingV2: "Komunikacijos nukreipimas",
    customerLifecycleV2: "Kliento kelias",
    securityHardeningV2: "Saugumo sustiprinimas",
  },
  en: {
    aiDrafts: "AI drafts",
    roofMeasurement: "Roof measurement",
    roofFusionV1: "Roof Fusion",
    customerQuotes: "Customer quotes",
    contractSigning: "Contract signing",
    workerPortal: "Worker portal",
    automatedReminders: "Automated reminders",
    seoScheduler: "Scheduled SEO work",
    caseStateEngineV2: "Case workflow",
    measurementEvidenceV2: "Measurement evidence",
    adminExceptionFlowsV2: "Exception handling",
    communicationRoutingV2: "Communication routing",
    customerLifecycleV2: "Customer lifecycle",
    securityHardeningV2: "Security hardening",
  },
};

export const integrationLabels: Record<
  PanelLocale,
  Record<IntegrationName, string>
> = {
  nb: {
    ai: "KI-tjeneste",
    email: "E-postutsending",
    sms: "SMS-utsending",
    maps: "Adresse- og kartdata",
    buildingFootprints: "Bygningsomriss",
    imagery: "Flyfoto",
    signature: "Elektronisk signering",
    legal: "Godkjente avtalevilkår",
    searchData: "Søkedata",
    stockImages: "Lisensierte bilder",
    jobs: "Bakgrunnsjobber",
    rateLimit: "Trafikkbegrensning",
    botProtection: "Botbeskyttelse",
    privateStorage: "Privat fillagring",
  },
  lt: {
    ai: "DI paslauga",
    email: "El. laiškų siuntimas",
    sms: "SMS siuntimas",
    maps: "Adresų ir žemėlapių duomenys",
    buildingFootprints: "Pastatų kontūrai",
    imagery: "Aeronuotraukos",
    signature: "Elektroninis pasirašymas",
    legal: "Patvirtintos sutarties sąlygos",
    searchData: "Paieškos duomenys",
    stockImages: "Licencijuotos nuotraukos",
    jobs: "Foninės užduotys",
    rateLimit: "Užklausų ribojimas",
    botProtection: "Apsauga nuo botų",
    privateStorage: "Privati failų saugykla",
  },
  en: {
    ai: "AI service",
    email: "Email delivery",
    sms: "SMS delivery",
    maps: "Address and map data",
    buildingFootprints: "Building footprints",
    imagery: "Aerial imagery",
    signature: "Electronic signing",
    legal: "Approved contract terms",
    searchData: "Search data",
    stockImages: "Licensed imagery",
    jobs: "Background jobs",
    rateLimit: "Traffic rate limiting",
    botProtection: "Bot protection",
    privateStorage: "Private file storage",
  },
};

const evidenceEnglish: Record<string, string> = {
  STAGING_QA_REFERENCE: "Documented staging QA",
  RESTORE_TEST_REFERENCE: "Documented recovery test",
  PRODUCTION_OWNER_APPROVAL_REFERENCE: "Product-owner approval",
  AI_CONTENT_PILOT_REFERENCE: "Approved AI-content pilot",
  ROOF_TECHNICAL_QA_REFERENCE: "Technical roof-measurement QA",
  ROOF_FUSION_V1_QA_REFERENCE: "Roof Fusion Preview QA",
  PRICING_APPROVAL_REFERENCE: "Pricing approval",
  QUOTE_JOURNEY_QA_REFERENCE: "Quote-journey QA",
  SIGNATURE_APPROVAL_REFERENCE: "Signing-solution approval",
  CONTRACT_JOURNEY_QA_REFERENCE: "Contract-journey QA",
  WORKER_MOBILE_QA_REFERENCE: "Worker-portal mobile QA",
  COMMUNICATION_APPROVAL_REFERENCE: "Automated-communication approval",
  SEO_PILOT_REFERENCE: "Approved SEO pilot",
  STATE_INVARIANT_QA_REFERENCE: "Case-workflow rule QA",
  ROOF_EVIDENCE_QA_REFERENCE: "Measurement-evidence QA",
  ADMIN_OPERATIONS_QA_REFERENCE: "Administrative-exception QA",
  COMMUNICATION_V2_QA_REFERENCE: "Communication-flow QA",
  CUSTOMER_LIFECYCLE_QA_REFERENCE: "Customer-lifecycle QA",
  SECURITY_HARDENING_QA_REFERENCE: "Security approval",
  ROOF_FUSION_V1_PRODUCTION_ACTIVATION_FORBIDDEN:
    "Roof Fusion is approved for Preview only and cannot be enabled in Production",
};

export const evidenceLabels: Record<PanelLocale, Record<string, string>> = {
  nb: {
    ...evidenceEnglish,
    STAGING_QA_REFERENCE: "Dokumentert staging-kontroll",
    RESTORE_TEST_REFERENCE: "Dokumentert gjenopprettingstest",
    PRODUCTION_OWNER_APPROVAL_REFERENCE: "Godkjenning fra produkteier",
    AI_CONTENT_PILOT_REFERENCE: "Godkjent pilot for KI-innhold",
    ROOF_TECHNICAL_QA_REFERENCE: "Teknisk QA for takmåling",
    ROOF_FUSION_V1_QA_REFERENCE: "QA for Roof Fusion i Preview",
    PRICING_APPROVAL_REFERENCE: "Prisgodkjenning",
    QUOTE_JOURNEY_QA_REFERENCE: "QA av tilbudsreisen",
    SIGNATURE_APPROVAL_REFERENCE: "Godkjenning av signeringsløsningen",
    CONTRACT_JOURNEY_QA_REFERENCE: "QA av kontraktsreisen",
    WORKER_MOBILE_QA_REFERENCE: "Mobil QA for medarbeiderportal",
    COMMUNICATION_APPROVAL_REFERENCE: "Godkjenning av automatisk kommunikasjon",
    SEO_PILOT_REFERENCE: "Godkjent SEO-pilot",
    STATE_INVARIANT_QA_REFERENCE: "QA av saksflytens regler",
    ROOF_EVIDENCE_QA_REFERENCE: "QA av målegrunnlag",
    ADMIN_OPERATIONS_QA_REFERENCE: "QA av administrativ avvikshåndtering",
    COMMUNICATION_V2_QA_REFERENCE: "QA av kommunikasjonsflyt",
    CUSTOMER_LIFECYCLE_QA_REFERENCE: "QA av kundereisen",
    SECURITY_HARDENING_QA_REFERENCE: "Sikkerhetsgodkjenning",
    ROOF_FUSION_V1_PRODUCTION_ACTIVATION_FORBIDDEN:
      "Roof Fusion er godkjent kun for Preview og kan ikke aktiveres i Production",
  },
  lt: {
    ...evidenceEnglish,
    STAGING_QA_REFERENCE: "Dokumentuota testinės aplinkos patikra",
    RESTORE_TEST_REFERENCE: "Dokumentuotas atkūrimo bandymas",
    PRODUCTION_OWNER_APPROVAL_REFERENCE: "Produkto savininko patvirtinimas",
    AI_CONTENT_PILOT_REFERENCE: "Patvirtintas DI turinio pilotas",
    ROOF_TECHNICAL_QA_REFERENCE: "Techninė stogo matavimo kokybės patikra",
    ROOF_FUSION_V1_QA_REFERENCE:
      "Roof Fusion kokybės patikra Preview aplinkoje",
    PRICING_APPROVAL_REFERENCE: "Kainodaros patvirtinimas",
    QUOTE_JOURNEY_QA_REFERENCE: "Pasiūlymo kelio kokybės patikra",
    SIGNATURE_APPROVAL_REFERENCE: "Pasirašymo sprendimo patvirtinimas",
    CONTRACT_JOURNEY_QA_REFERENCE: "Sutarties kelio kokybės patikra",
    WORKER_MOBILE_QA_REFERENCE: "Darbuotojo portalo mobili patikra",
    COMMUNICATION_APPROVAL_REFERENCE: "Automatinės komunikacijos patvirtinimas",
    SEO_PILOT_REFERENCE: "Patvirtintas SEO pilotas",
    STATE_INVARIANT_QA_REFERENCE: "Bylos eigos taisyklių kokybės patikra",
    ROOF_EVIDENCE_QA_REFERENCE: "Matavimo įrodymų kokybės patikra",
    ADMIN_OPERATIONS_QA_REFERENCE: "Administracinių išimčių kokybės patikra",
    COMMUNICATION_V2_QA_REFERENCE: "Komunikacijos eigos kokybės patikra",
    CUSTOMER_LIFECYCLE_QA_REFERENCE: "Kliento kelio kokybės patikra",
    SECURITY_HARDENING_QA_REFERENCE: "Saugumo patvirtinimas",
    ROOF_FUSION_V1_PRODUCTION_ACTIVATION_FORBIDDEN:
      "Roof Fusion patvirtintas tik Preview ir negali būti įjungtas Production",
  },
  en: evidenceEnglish,
};

export const stateLabels: Record<
  PanelLocale,
  Record<AdminNextCapabilityState, string>
> = {
  nb: {
    legacy_active: "Dagens funksjon er aktiv",
    implemented_disabled: "Implementert, men ikke aktivert",
    blocked_configuration: "Venter på konfigurasjon",
    preview_ready: "Tilgjengelig for Preview-test",
    enabled: "Aktivert for full drift",
    planned: "Planlagt",
  },
  lt: {
    legacy_active: "Veikia dabartinė funkcija",
    implemented_disabled: "Įgyvendinta, bet neįjungta",
    blocked_configuration: "Laukia konfigūracijos",
    preview_ready: "Pasiekiama Preview testui",
    enabled: "Įjungta pilnam veikimui",
    planned: "Suplanuota",
  },
  en: {
    legacy_active: "Current function is active",
    implemented_disabled: "Implemented but not enabled",
    blocked_configuration: "Waiting for configuration",
    preview_ready: "Available for Preview testing",
    enabled: "Enabled for full operation",
    planned: "Planned",
  },
};
