import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { BlogGenerateButton } from "@/components/admin-v2/blog-generate-button";
import { getAdminV2Copy } from "@/lib/admin-v2/i18n";
import { statusLabel } from "@/lib/admin-v2/labels";
import { requireAdminUser } from "@/lib/auth/internal-session";
import { panelDateLocale } from "@/lib/panel-i18n";
import { getPayload } from "@/lib/payload";

export const dynamic="force-dynamic";
export default async function BlogAdminPage(){const user=await requireAdminUser();const copy=getAdminV2Copy(user.interfaceLanguage);const result=await (await getPayload()).find({collection:"posts",depth:1,draft:true,limit:200,pagination:false,overrideAccess:true,sort:"-updatedAt"});const formatter=new Intl.DateTimeFormat(panelDateLocale(user.interfaceLanguage),{dateStyle:"medium",timeStyle:"short"});return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-accent">{copy.control}</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{copy.blogAdmin.title}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{copy.blogAdmin.intro}</p></div><BlogGenerateButton locale={user.interfaceLanguage}/></header>{result.docs.length?<div className="grid gap-3">{result.docs.map(post=><Link className="group grid gap-3 rounded-3xl border border-white/10 bg-background-elevated/75 p-5 transition hover:border-accent/45 sm:grid-cols-[1fr_auto] sm:items-center" href={`/admin-v2/blog/${post.id}`} key={post.id}><span className="min-w-0"><span className="rounded-full border border-accent/25 bg-accent/10 px-2.5 py-1 text-xs font-bold uppercase tracking-wider text-accent">{statusLabel(user.interfaceLanguage,post.editorialStatus)}</span><strong className="mt-3 block truncate text-lg">{post.titleNo}</strong><span className="mt-1 block truncate text-sm text-muted-foreground">{post.primaryKeyword||post.excerptNo||post.slug}</span><span className="mt-2 block text-xs text-muted-foreground">{formatter.format(new Date(post.updatedAt))}{typeof post.qualityScore==="number"?` · ${copy.blogAdmin.quality}: ${post.qualityScore}`:""}</span></span><span className="inline-flex items-center gap-2 font-bold text-accent">{copy.blogAdmin.open}<ArrowRight aria-hidden="true" className="size-4 transition group-hover:translate-x-1"/></span></Link>)}</div>:<div className="rounded-3xl border border-dashed border-white/15 p-8 text-center text-muted-foreground">{copy.blogAdmin.empty}</div>}</div>}
