/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    products: Product;
    faq: Faq;
    pages: Page;
    posts: Post;
    redirects: Redirect;
    leads: Lead;
    messages: Message;
    'roof-measurements': RoofMeasurement;
    'price-rules': PriceRule;
    'price-calculations': PriceCalculation;
    quotes: Quote;
    contracts: Contract;
    'change-agreements': ChangeAgreement;
    'contract-terms': ContractTerm;
    'work-orders': WorkOrder;
    'invoice-records': InvoiceRecord;
    warranties: Warranty;
    'seo-topics': SeoTopic;
    'seo-runs': SeoRun;
    'audit-events': AuditEvent;
    'operational-jobs': OperationalJob;
    'access-tokens': AccessToken;
    'private-media': PrivateMedia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'roof-measurements': RoofMeasurementsSelect<false> | RoofMeasurementsSelect<true>;
    'price-rules': PriceRulesSelect<false> | PriceRulesSelect<true>;
    'price-calculations': PriceCalculationsSelect<false> | PriceCalculationsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    'change-agreements': ChangeAgreementsSelect<false> | ChangeAgreementsSelect<true>;
    'contract-terms': ContractTermsSelect<false> | ContractTermsSelect<true>;
    'work-orders': WorkOrdersSelect<false> | WorkOrdersSelect<true>;
    'invoice-records': InvoiceRecordsSelect<false> | InvoiceRecordsSelect<true>;
    warranties: WarrantiesSelect<false> | WarrantiesSelect<true>;
    'seo-topics': SeoTopicsSelect<false> | SeoTopicsSelect<true>;
    'seo-runs': SeoRunsSelect<false> | SeoRunsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'operational-jobs': OperationalJobsSelect<false> | OperationalJobsSelect<true>;
    'access-tokens': AccessTokensSelect<false> | AccessTokensSelect<true>;
    'private-media': PrivateMediaSelect<false> | PrivateMediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Opprett egne kontoer for ansatte. Deaktivering avslutter aktive sesjoner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Navnet som vises i arbeidsoversikten.
   */
  displayName?: string | null;
  phone?: string | null;
  /**
   * Gjelder bare /user. Kundetekster, tilbud og kontrakter forblir på norsk.
   */
  interfaceLanguage: 'nb' | 'lt' | 'en';
  role: 'admin' | 'worker';
  /**
   * Slå av for å stanse innlogging og tilbakekalle aktive sesjoner.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images here (stored on Vercel Blob). Then pick them in Site Settings or Project stages. Prefer WebP when possible; large JPEG/PNG are auto-converted when supported.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description for accessibility / SEO
   */
  alt: string;
  stockProvider?: ('manual' | 'pexels') | null;
  stockAssetId?: string | null;
  stockSourceUrl?: string | null;
  stockPhotographer?: string | null;
  stockPhotographerUrl?: string | null;
  stockLicenseUrl?: string | null;
  stockRetrievedAt?: string | null;
  stockQuery?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  key: string;
  titleNo: string;
  titleEn: string;
  descriptionNo: string;
  descriptionEn: string;
  icon?: ('check' | 'shield' | 'droplets' | 'paint' | 'home' | 'wrench' | 'sparkles') | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  titleNo: string;
  titleEn: string;
  order?: number | null;
  stages?:
    | {
        label: 'before' | 'during' | 'after';
        captionNo: string;
        captionEn: string;
        /**
         * Upload via Media library (Vercel Blob). Preferred.
         */
        image?: (number | null) | Media;
        /**
         * Used only if no uploaded image is selected
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  categoryNo: string;
  categoryEn: string;
  descriptionNo: string;
  descriptionEn: string;
  image?: (number | null) | Media;
  badgesNo?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  badgesEn?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  questionNo: string;
  questionEn: string;
  answerNo: string;
  answerEn: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Lowercase URL segment. “blogg” and “personvern” are reserved.
   */
  slug: string;
  titleNo: string;
  titleEn: string;
  excerptNo?: string | null;
  excerptEn?: string | null;
  /**
   * Plain text with optional Markdown-style ## headings and - lists.
   */
  contentNo: string;
  /**
   * Plain text with optional Markdown-style ## headings and - lists.
   */
  contentEn: string;
  seoTitleNo?: string | null;
  seoTitleEn?: string | null;
  seoDescriptionNo?: string | null;
  seoDescriptionEn?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Lowercase URL segment below /blogg.
   */
  slug: string;
  titleNo: string;
  titleEn?: string | null;
  excerptNo?: string | null;
  excerptEn?: string | null;
  /**
   * Safe Markdown: ## headings, lists, **bold** and [link text](https://...). HTML is not rendered.
   */
  contentNo: string;
  /**
   * Leave empty until a complete English version has been reviewed.
   */
  contentEn?: string | null;
  heroImage?: (number | null) | Media;
  seoTitleNo?: string | null;
  seoTitleEn?: string | null;
  seoDescriptionNo?: string | null;
  seoDescriptionEn?: string | null;
  publishedAt?: string | null;
  editorialStatus: 'draft' | 'ai_qa' | 'human_review' | 'rejected' | 'approved' | 'scheduled' | 'published';
  /**
   * Kan bare lagres når redaksjonell status er Godkjent eller Planlagt.
   */
  scheduledAt?: string | null;
  searchIntent?: ('informational' | 'commercial' | 'local' | 'comparison') | null;
  primaryKeyword?: string | null;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  primaryService?: (number | null) | Service;
  locationText?: string | null;
  category?: string | null;
  sources?:
    | {
        label: string;
        url: string;
        publisher?: string | null;
        accessedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  authorName?: string | null;
  reviewerName?: string | null;
  reviewedAt?: string | null;
  aiAssisted?: boolean | null;
  aiGenerationRun?: (number | null) | SeoRun;
  qualityScore?: number | null;
  qualityChecks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewFlags?:
    | {
        flag: string;
        id?: string | null;
      }[]
    | null;
  proposedInternalLinks?:
    | {
        href: string;
        anchor: string;
        reason: string;
        id?: string | null;
      }[]
    | null;
  imageBrief?: string | null;
  imageAlt?: string | null;
  /**
   * Fylles automatisk fra Pexels. Et manuelt opplastet hovedbilde overstyrer dette bildet.
   */
  stockImage?: {
    provider?: string | null;
    assetId?: string | null;
    imageUrl?: string | null;
    sourceUrl?: string | null;
    photographer?: string | null;
    photographerUrl?: string | null;
    licenseUrl?: string | null;
    query?: string | null;
    selectedAt?: string | null;
  };
  relatedPosts?: (number | Post)[] | null;
  relatedServices?: (number | Service)[] | null;
  ctaVariant?: ('assessment' | 'wash' | 'renewal' | 'new_roof') | null;
  faqItems?:
    | {
        questionNo: string;
        answerNo: string;
        questionEn?: string | null;
        answerEn?: string | null;
        id?: string | null;
      }[]
    | null;
  lastContentAuditAt?: string | null;
  leadPerformance?: {
    leads?: number | null;
    convertedLeads?: number | null;
    updatedAt?: string | null;
  };
  searchPerformance?: {
    impressions?: number | null;
    clicks?: number | null;
    ctr?: number | null;
    averagePosition?: number | null;
    updatedAt?: string | null;
    indexVerdict?: string | null;
    coverageState?: string | null;
    lastCrawlAt?: string | null;
  };
  performanceNotes?: string | null;
  /**
   * Systemets anbefaling er beslutningsstøtte. Administrator må kontrollere og utføre eventuell endring.
   */
  contentAudit?: {
    recommendation?: ('keep' | 'update' | 'merge' | 'redirect') | null;
    reason?: string | null;
    generatedAt?: string | null;
    targetPost?: (number | null) | Post;
    reviewedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ikke-sensitive spor for temavalg, utkast og kvalitetssjekk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-runs".
 */
export interface SeoRun {
  id: number;
  idempotencyKey: string;
  jobType: string;
  triggerSource: 'manual' | 'cron' | 'regenerate';
  weekKey?: string | null;
  slot?: string | null;
  status: 'running' | 'completed' | 'failed' | 'attention';
  startedAt: string;
  finishedAt?: string | null;
  selectedTopics?: (number | SeoTopic)[] | null;
  rejectedTopics?: (number | SeoTopic)[] | null;
  modelVersion?: string | null;
  promptVersion?: string | null;
  knowledgeVersion?: string | null;
  qualityResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorCode?: string | null;
  /**
   * Sanitert feiltekst uten prompts, nøkler eller kundedata.
   */
  errorMessage?: string | null;
  createdPost?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-topics".
 */
export interface SeoTopic {
  id: number;
  fingerprint: string;
  topic: string;
  primaryKeyword: string;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  searchIntent: 'informational' | 'commercial' | 'local' | 'comparison';
  service?: (number | null) | Service;
  location?: string | null;
  season?: string | null;
  source: 'search_console' | 'ads' | 'trends' | 'lead' | 'manual';
  /**
   * Kun aggregerte tall; aldri kundedata eller tokens.
   */
  sourceMetrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Kan opprettes uten AI og må kontrolleres før artikkelgenerering.
   */
  proposedBrief?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  topicScore: number;
  overlapScore: number;
  scoreBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rejectionReasons?:
    | {
        reason: string;
        id?: string | null;
      }[]
    | null;
  reasonForSelection: string;
  status: 'candidate' | 'rejected' | 'queued' | 'drafted' | 'approved' | 'published';
  checkedAt?: string | null;
  relatedPost?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redirects are currently resolved for CMS page slugs and blog post routes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Locale-specific (/no/gammel) or locale-neutral (/gammel) source path.
   */
  fromPath: string;
  /**
   * Internal destination beginning with /.
   */
  toPath?: string | null;
  toUrl?: string | null;
  /**
   * Permanent redirects use HTTP 308; temporary ones use 307.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  preferredChannel?: ('email' | 'sms') | null;
  address: string;
  houseNumber?: string | null;
  postal: string;
  city?: string | null;
  approxSqm?: number | null;
  /**
   * Lead photos from the website form. Previews work in admin; direct Blob links are private.
   */
  photoUrls?: string | null;
  inquiryType:
    | 'takvask'
    | 'takvask_impregnering'
    | 'impregnering'
    | 'takmaling'
    | 'nytt_tak'
    | 'usikker'
    | 'vedlikehold'
    | 'kledning';
  message?: string | null;
  language: 'no' | 'en';
  status?:
    | (
        | 'new'
        | 'draft_ready'
        | 'customer_waiting'
        | 'waiting_customer'
        | 'qualified'
        | 'measuring'
        | 'quoted'
        | 'converted'
        | 'closed'
        | 'contacted'
      )
    | null;
  recordState: 'active' | 'archived' | 'trashed';
  archiveClassification?: ('completed' | 'declined' | 'lost' | 'invalid' | 'spam' | 'duplicate' | 'other') | null;
  archiveReason?: string | null;
  archivedAt?: string | null;
  archivedBy?: (number | null) | User;
  trashedAt?: string | null;
  trashedBy?: (number | null) | User;
  purgeAfter?: string | null;
  assignedTo?: (number | null) | User;
  nextAction?: string | null;
  nextActionAt?: string | null;
  nextActionOwner: 'administrator' | 'customer' | 'system' | 'worker';
  nextActionBlocker?: string | null;
  caseRevision: number;
  lastContactAt?: string | null;
  adminReviewedAt?: string | null;
  adminReviewedBy?: (number | null) | User;
  closedAt?: string | null;
  qualification?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When the visitor accepted the privacy consent checkbox.
   */
  consentAt?: string | null;
  /**
   * Exact consent label shown at submit time.
   */
  consentText?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  gclid?: string | null;
  gbraid?: string | null;
  wbraid?: string | null;
  fbclid?: string | null;
  msclkid?: string | null;
  landingPage?: string | null;
  /**
   * Last blog article CTA used before this inquiry.
   */
  contentSourcePath?: string | null;
  referrer?: string | null;
  marketingConsent?: ('granted' | 'denied' | 'unknown') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundekommunikasjon med kontrollert godkjenning og idempotent levering.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  lead?: (number | null) | Lead;
  replyToMessage?: (number | null) | Message;
  direction: 'outbound' | 'inbound';
  category:
    | 'receipt'
    | 'ai_reply'
    | 'information_request'
    | 'follow_up'
    | 'quote'
    | 'contract'
    | 'customer_question'
    | 'change_agreement'
    | 'change_confirmation'
    | 'measurement_confirmation'
    | 'schedule_confirmation'
    | 'completion'
    | 'reminder';
  channel: 'email' | 'sms';
  subject: string;
  bodyText: string;
  bodyHtml?: string | null;
  /**
   * Private, varige dokumenter lagt ved av kontrollert arbeidsflyt.
   */
  attachments?: (number | PrivateMedia)[] | null;
  status: 'draft' | 'approved' | 'queued' | 'sent' | 'delivered' | 'failed' | 'attention' | 'cancelled';
  idempotencyKey: string;
  aiAssisted?: boolean | null;
  aiAnalysis?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  modelVersion?: string | null;
  promptVersion?: string | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  queuedAt?: string | null;
  sentAt?: string | null;
  deliveredAt?: string | null;
  provider?: string | null;
  providerMessageId?: string | null;
  failureCode?: string | null;
  /**
   * Sanitert teknisk tekst uten kontaktdata eller meldingsinnhold.
   */
  failureMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer, contract and work files. Access must always be authorized server-side.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media".
 */
export interface PrivateMedia {
  id: number;
  classification: 'customer' | 'measurement' | 'contract' | 'work' | 'invoice' | 'warranty';
  ownerType?: string | null;
  ownerId?: string | null;
  /**
   * Required when the file is an image shown in UI.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Versjonerte takmålinger. AI kan foreslå; geometri og pris beregnes av kode og må godkjennes av administrator.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roof-measurements".
 */
export interface RoofMeasurement {
  id: number;
  reference: string;
  lead: number | Lead;
  version: number;
  supersedes?: (number | null) | RoofMeasurement;
  measurementMode: 'schematic' | 'schematic_with_context' | 'manual_no_visual';
  normalizedAddress: string;
  addressSourceId?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  buildingIdentifier?: string | null;
  source: string;
  sourceUrl?: string | null;
  license: string;
  credits: string;
  /**
   * Teknisk legacy-feltnavn. Gjelder både åpne bygningskonturer og bilder; aktiveres bare når kilden kan brukes og korrekt kreditering er registrert.
   */
  imageryLicensed: boolean;
  capturedAt: string;
  mapImage?: (number | null) | PrivateMedia;
  /**
   * Kandidater som var tilgjengelige da måleversjonen ble opprettet.
   */
  candidateBuildings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  evidenceSnapshot?: (number | null) | PrivateMedia;
  evidenceHash?: string | null;
  evidenceSource?: string | null;
  evidenceAttribution?: string | null;
  evidenceGeneratedAt?: string | null;
  imageryCapturedAt?: string | null;
  selectionConfirmedBy?: (number | null) | User;
  selectionConfirmedAt?: string | null;
  manualAreaSource?: ('customer' | 'drawing' | 'admin_estimate' | 'onsite') | null;
  manualAreaReason?: string | null;
  /**
   * Polygonpunkter (lat/lon) og vinkelintervall per takflate. Redigering oppretter ny versjon via kontrollen under.
   */
  roofPlanes:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 0,1 m²
   */
  horizontalAreaTenths: number;
  /**
   * 0,1 m²
   */
  actualAreaMinTenths: number;
  /**
   * 0,1 m²
   */
  actualAreaMaxTenths: number;
  calculationSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  inputHash: string;
  confidence: 'high' | 'medium' | 'low';
  confidenceReasoning: string;
  status: 'draft' | 'review_required' | 'blocked' | 'approved' | 'superseded';
  blockingReasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kun godkjente, versjonerte regler kan brukes. Markedsføringspriser er ikke automatisk bindende prisregler.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-rules".
 */
export interface PriceRule {
  id: number;
  reference: string;
  version: number;
  serviceKey: 'takvask' | 'takvask_impregnering' | 'impregnering' | 'takmaling' | 'nytt_tak';
  unitPriceExVatOre: number;
  vatBasisPoints: number;
  minimumExVatOre: number;
  toleranceBasisPoints: number;
  maximumExVatOre?: number | null;
  validFrom: string;
  validTo?: string | null;
  termsVersion: string;
  notes?: string | null;
  status: 'draft' | 'approved' | 'retired';
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uforanderlige beregningsspor. AI kan bare forklare tall som allerede er beregnet her.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-calculations".
 */
export interface PriceCalculation {
  id: number;
  reference: string;
  lead: number | Lead;
  measurement: number | RoofMeasurement;
  priceRule: number | PriceRule;
  inputSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  outputSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  inputHash: string;
  subtotalExVatOre: number;
  vatOre: number;
  totalIncVatOre: number;
  maximumTotalIncVatOre?: number | null;
  status: 'draft' | 'ready' | 'blocked' | 'superseded';
  blockingReasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Versjonerte kundetilbud låst til godkjent måling og prisberegning.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  reference: string;
  lead: number | Lead;
  measurement: number | RoofMeasurement;
  priceCalculation: number | PriceCalculation;
  version: number;
  supersedes?: (number | null) | Quote;
  optionGroup?: string | null;
  optionKind?: ('base' | 'recommended') | null;
  siblingQuote?: (number | null) | Quote;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  snapshotHash: string;
  serviceDescription: string;
  totalIncVatOre: number;
  maximumTotalIncVatOre?: number | null;
  termsVersion: string;
  validUntil: string;
  status: 'draft' | 'approved' | 'sent' | 'viewed' | 'accepted' | 'declined' | 'expired' | 'revoked' | 'superseded';
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  selectedOptionQuote?: (number | null) | Quote;
  sentAt?: string | null;
  viewedAt?: string | null;
  acceptedAt?: string | null;
  declinedAt?: string | null;
  declineReason?: string | null;
  declineComment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Låste kontraktsdokumenter med hash, samtykker og signaturbevis.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  reference: string;
  quote: number | Quote;
  version: number;
  supersedes?: (number | null) | Contract;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  documentHash: string;
  termsVersion: string;
  status: 'draft' | 'issued' | 'signed' | 'declined' | 'revoked' | 'superseded';
  /**
   * Kundens signaturbevis.
   */
  signatureEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  customerSignatureImage?: (number | null) | PrivateMedia;
  /**
   * Kundesignert dokument som avventer leverandørens signatur.
   */
  signedDocument?: (number | null) | PrivateMedia;
  /**
   * Tidspunkt kunden signerte.
   */
  signedAt?: string | null;
  /**
   * Leverandørens signaturbevis.
   */
  companySignatureEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  companySignatureImage?: (number | null) | PrivateMedia;
  /**
   * Endelig kontrakt signert av begge parter.
   */
  companySignedDocument?: (number | null) | PrivateMedia;
  companySignedAt?: string | null;
  companySignedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Versjonerte pris-/omfangsendringer som krever admin og skriftlig kundegodkjenning.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-agreements".
 */
export interface ChangeAgreement {
  id: number;
  reference: string;
  workOrder: number | WorkOrder;
  contract: number | Contract;
  version: number;
  supersedes?: (number | null) | ChangeAgreement;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  documentHash: string;
  reasonCode: 'over_tolerance' | 'over_maximum' | 'scope_change';
  reasonDescription: string;
  beforeTotalIncVatOre: number;
  afterTotalIncVatOre: number;
  validUntil: string;
  status: 'draft' | 'approved' | 'sent' | 'viewed' | 'accepted' | 'declined' | 'revoked' | 'superseded';
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  sentAt?: string | null;
  viewedAt?: string | null;
  acceptanceEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  acceptedDocument?: (number | null) | PrivateMedia;
  acceptedAt?: string | null;
  declinedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tildeling, kontrollmåling, HMS, prisbekreftelse og før-/etterdokumentasjon for signerte oppdrag.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-orders".
 */
export interface WorkOrder {
  id: number;
  reference: string;
  lead: number | Lead;
  quote: number | Quote;
  contract: number | Contract;
  contractDocumentHash: string;
  assignedWorker?: (number | null) | User;
  scheduledAt?: string | null;
  /**
   * For eksempel 08:00–10:00. Vis nøyaktig avtalt tidsrom, ikke et løfte som ikke kan holdes.
   */
  arrivalWindow?: string | null;
  /**
   * Kun internt. Ikke sendt til kunden.
   */
  adminNote?: string | null;
  customerCancellationRequestedAt?: string | null;
  cancellationRequestMessage?: (number | null) | Message;
  statusBeforeCustomerCancellation?: string | null;
  customerCancellationResolvedAt?: string | null;
  customerCancellationResolution?: string | null;
  status:
    | 'unassigned'
    | 'assigned'
    | 'scheduled'
    | 'on_way'
    | 'arrived'
    | 'precheck'
    | 'ready'
    | 'blocked'
    | 'in_progress'
    | 'completed'
    | 'documented'
    | 'cancelled';
  workSummary: string;
  beforePhotos?: (number | PrivateMedia)[] | null;
  roofType?: ('betongstein' | 'teglstein' | 'metall' | 'skifer' | 'shingel' | 'annet') | null;
  actualAreaTenths?: number | null;
  measurementMethod?: ('laser' | 'målebånd' | 'tegning' | 'kart_kontrollert' | 'annet') | null;
  slopeBasis?: string | null;
  visibleCondition?: string | null;
  safetyStatus?: ('safe' | 'blocked') | null;
  safetyNotes?: string | null;
  scopeChanged?: boolean | null;
  scopeChangeDetails?: string | null;
  precheckDecision?: ('ready' | 'blocked') | null;
  priceOutcome?:
    ('lower' | 'within_contract' | 'over_tolerance' | 'over_maximum' | 'scope_change' | 'hms_blocked') | null;
  allowedAreaMaxTenths?: number | null;
  actualSubtotalExVatOre?: number | null;
  actualVatOre?: number | null;
  actualTotalIncVatOre?: number | null;
  blockingReasons?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approvedChangeAgreement?: (number | null) | ChangeAgreement;
  precheckCompletedAt?: string | null;
  startedAt?: string | null;
  afterPhotos?: (number | PrivateMedia)[] | null;
  completionNotes?: string | null;
  completedAt?: string | null;
  documentationSubmittedAt?: string | null;
  completionReviewedBy?: (number | null) | User;
  completionReviewedAt?: string | null;
  completionReviewNote?: string | null;
  /**
   * Systemstyrte hendelser uten kundeopplysninger.
   */
  eventTimeline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Versjonerte vilkår. Produksjonsgodkjenning krever dokumentert juridisk referanse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-terms".
 */
export interface ContractTerm {
  id: number;
  version: string;
  title: string;
  contractText: string;
  withdrawalInstructions: string;
  withdrawalFormUrl: string;
  status: 'draft' | 'approved' | 'retired';
  legalReviewReference?: string | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Interne fakturautkast. Ikke bokført faktura før godkjent eksport til valgt regnskapssystem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-records".
 */
export interface InvoiceRecord {
  id: number;
  reference: string;
  lead: number | Lead;
  workOrder: number | WorkOrder;
  status: 'draft' | 'approved' | 'exported' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  documentHash: string;
  subtotalExVatOre: number;
  vatOre: number;
  totalIncVatOre: number;
  issuedAt: string;
  dueAt: string;
  assignedTo: number | User;
  externalReference?: string | null;
  adminNote?: string | null;
  document?: (number | null) | PrivateMedia;
  approvedAt?: string | null;
  sentAt?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Saksbekreftede garantier. Omfang og varighet må kontrolleres av administrator før aktivering.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranties".
 */
export interface Warranty {
  id: number;
  reference: string;
  lead: number | Lead;
  workOrder: number | WorkOrder;
  status: 'active' | 'expired' | 'revoked';
  scope: string;
  startsAt: string;
  endsAt: string;
  termsVersion: string;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  documentHash: string;
  document?: (number | null) | PrivateMedia;
  approvedBy: number | User;
  approvedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable operational audit trail. Sensitive values and raw customer data must not be stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor?: (number | null) | User;
  action: string;
  entityType: string;
  entityId: string;
  correlationId: string;
  /**
   * Field names only; never raw before/after values.
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  beforeHash?: string | null;
  afterHash?: string | null;
  /**
   * Allow-listed operational identifiers only. No names, addresses, contact details, secrets or tokens.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Retryable jobs and outbox operations. Payload must contain IDs, not raw customer data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-jobs".
 */
export interface OperationalJob {
  id: number;
  type: string;
  status: 'pending' | 'running' | 'retry' | 'completed' | 'failed' | 'attention' | 'cancelled';
  idempotencyKey: string;
  correlationId: string;
  attempts: number;
  maxAttempts: number;
  availableAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  lastErrorCode?: string | null;
  /**
   * Sanitized operational message; no raw payload.
   */
  lastErrorMessage?: string | null;
  /**
   * References and non-sensitive job options only. Do not copy lead data here.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hashed tokens for customer links. Plain-text tokens are never persisted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-tokens".
 */
export interface AccessToken {
  id: number;
  purpose: string;
  tokenHash: string;
  subjectType: string;
  subjectId: string;
  expiresAt: string;
  revokedAt?: string | null;
  usedAt?: string | null;
  singleUse?: boolean | null;
  /**
   * Non-sensitive operational metadata only. Never store the plain token.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'roof-measurements';
        value: number | RoofMeasurement;
      } | null)
    | ({
        relationTo: 'price-rules';
        value: number | PriceRule;
      } | null)
    | ({
        relationTo: 'price-calculations';
        value: number | PriceCalculation;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'change-agreements';
        value: number | ChangeAgreement;
      } | null)
    | ({
        relationTo: 'contract-terms';
        value: number | ContractTerm;
      } | null)
    | ({
        relationTo: 'work-orders';
        value: number | WorkOrder;
      } | null)
    | ({
        relationTo: 'invoice-records';
        value: number | InvoiceRecord;
      } | null)
    | ({
        relationTo: 'warranties';
        value: number | Warranty;
      } | null)
    | ({
        relationTo: 'seo-topics';
        value: number | SeoTopic;
      } | null)
    | ({
        relationTo: 'seo-runs';
        value: number | SeoRun;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'operational-jobs';
        value: number | OperationalJob;
      } | null)
    | ({
        relationTo: 'access-tokens';
        value: number | AccessToken;
      } | null)
    | ({
        relationTo: 'private-media';
        value: number | PrivateMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  phone?: T;
  interfaceLanguage?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  stockProvider?: T;
  stockAssetId?: T;
  stockSourceUrl?: T;
  stockPhotographer?: T;
  stockPhotographerUrl?: T;
  stockLicenseUrl?: T;
  stockRetrievedAt?: T;
  stockQuery?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  key?: T;
  titleNo?: T;
  titleEn?: T;
  descriptionNo?: T;
  descriptionEn?: T;
  icon?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  titleNo?: T;
  titleEn?: T;
  order?: T;
  stages?:
    | T
    | {
        label?: T;
        captionNo?: T;
        captionEn?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  categoryNo?: T;
  categoryEn?: T;
  descriptionNo?: T;
  descriptionEn?: T;
  image?: T;
  badgesNo?:
    | T
    | {
        label?: T;
        id?: T;
      };
  badgesEn?:
    | T
    | {
        label?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  questionNo?: T;
  questionEn?: T;
  answerNo?: T;
  answerEn?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  titleNo?: T;
  titleEn?: T;
  excerptNo?: T;
  excerptEn?: T;
  contentNo?: T;
  contentEn?: T;
  seoTitleNo?: T;
  seoTitleEn?: T;
  seoDescriptionNo?: T;
  seoDescriptionEn?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  titleNo?: T;
  titleEn?: T;
  excerptNo?: T;
  excerptEn?: T;
  contentNo?: T;
  contentEn?: T;
  heroImage?: T;
  seoTitleNo?: T;
  seoTitleEn?: T;
  seoDescriptionNo?: T;
  seoDescriptionEn?: T;
  publishedAt?: T;
  editorialStatus?: T;
  scheduledAt?: T;
  searchIntent?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  primaryService?: T;
  locationText?: T;
  category?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        publisher?: T;
        accessedAt?: T;
        id?: T;
      };
  authorName?: T;
  reviewerName?: T;
  reviewedAt?: T;
  aiAssisted?: T;
  aiGenerationRun?: T;
  qualityScore?: T;
  qualityChecks?: T;
  reviewFlags?:
    | T
    | {
        flag?: T;
        id?: T;
      };
  proposedInternalLinks?:
    | T
    | {
        href?: T;
        anchor?: T;
        reason?: T;
        id?: T;
      };
  imageBrief?: T;
  imageAlt?: T;
  stockImage?:
    | T
    | {
        provider?: T;
        assetId?: T;
        imageUrl?: T;
        sourceUrl?: T;
        photographer?: T;
        photographerUrl?: T;
        licenseUrl?: T;
        query?: T;
        selectedAt?: T;
      };
  relatedPosts?: T;
  relatedServices?: T;
  ctaVariant?: T;
  faqItems?:
    | T
    | {
        questionNo?: T;
        answerNo?: T;
        questionEn?: T;
        answerEn?: T;
        id?: T;
      };
  lastContentAuditAt?: T;
  leadPerformance?:
    | T
    | {
        leads?: T;
        convertedLeads?: T;
        updatedAt?: T;
      };
  searchPerformance?:
    | T
    | {
        impressions?: T;
        clicks?: T;
        ctr?: T;
        averagePosition?: T;
        updatedAt?: T;
        indexVerdict?: T;
        coverageState?: T;
        lastCrawlAt?: T;
      };
  performanceNotes?: T;
  contentAudit?:
    | T
    | {
        recommendation?: T;
        reason?: T;
        generatedAt?: T;
        targetPost?: T;
        reviewedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  toUrl?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  preferredChannel?: T;
  address?: T;
  houseNumber?: T;
  postal?: T;
  city?: T;
  approxSqm?: T;
  photoUrls?: T;
  inquiryType?: T;
  message?: T;
  language?: T;
  status?: T;
  recordState?: T;
  archiveClassification?: T;
  archiveReason?: T;
  archivedAt?: T;
  archivedBy?: T;
  trashedAt?: T;
  trashedBy?: T;
  purgeAfter?: T;
  assignedTo?: T;
  nextAction?: T;
  nextActionAt?: T;
  nextActionOwner?: T;
  nextActionBlocker?: T;
  caseRevision?: T;
  lastContactAt?: T;
  adminReviewedAt?: T;
  adminReviewedBy?: T;
  closedAt?: T;
  qualification?: T;
  consentAt?: T;
  consentText?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  utmTerm?: T;
  gclid?: T;
  gbraid?: T;
  wbraid?: T;
  fbclid?: T;
  msclkid?: T;
  landingPage?: T;
  contentSourcePath?: T;
  referrer?: T;
  marketingConsent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  lead?: T;
  replyToMessage?: T;
  direction?: T;
  category?: T;
  channel?: T;
  subject?: T;
  bodyText?: T;
  bodyHtml?: T;
  attachments?: T;
  status?: T;
  idempotencyKey?: T;
  aiAssisted?: T;
  aiAnalysis?: T;
  modelVersion?: T;
  promptVersion?: T;
  approvedBy?: T;
  approvedAt?: T;
  queuedAt?: T;
  sentAt?: T;
  deliveredAt?: T;
  provider?: T;
  providerMessageId?: T;
  failureCode?: T;
  failureMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roof-measurements_select".
 */
export interface RoofMeasurementsSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  version?: T;
  supersedes?: T;
  measurementMode?: T;
  normalizedAddress?: T;
  addressSourceId?: T;
  latitude?: T;
  longitude?: T;
  buildingIdentifier?: T;
  source?: T;
  sourceUrl?: T;
  license?: T;
  credits?: T;
  imageryLicensed?: T;
  capturedAt?: T;
  mapImage?: T;
  candidateBuildings?: T;
  evidenceSnapshot?: T;
  evidenceHash?: T;
  evidenceSource?: T;
  evidenceAttribution?: T;
  evidenceGeneratedAt?: T;
  imageryCapturedAt?: T;
  selectionConfirmedBy?: T;
  selectionConfirmedAt?: T;
  manualAreaSource?: T;
  manualAreaReason?: T;
  roofPlanes?: T;
  horizontalAreaTenths?: T;
  actualAreaMinTenths?: T;
  actualAreaMaxTenths?: T;
  calculationSnapshot?: T;
  inputHash?: T;
  confidence?: T;
  confidenceReasoning?: T;
  status?: T;
  blockingReasons?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-rules_select".
 */
export interface PriceRulesSelect<T extends boolean = true> {
  reference?: T;
  version?: T;
  serviceKey?: T;
  unitPriceExVatOre?: T;
  vatBasisPoints?: T;
  minimumExVatOre?: T;
  toleranceBasisPoints?: T;
  maximumExVatOre?: T;
  validFrom?: T;
  validTo?: T;
  termsVersion?: T;
  notes?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-calculations_select".
 */
export interface PriceCalculationsSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  measurement?: T;
  priceRule?: T;
  inputSnapshot?: T;
  outputSnapshot?: T;
  inputHash?: T;
  subtotalExVatOre?: T;
  vatOre?: T;
  totalIncVatOre?: T;
  maximumTotalIncVatOre?: T;
  status?: T;
  blockingReasons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  measurement?: T;
  priceCalculation?: T;
  version?: T;
  supersedes?: T;
  optionGroup?: T;
  optionKind?: T;
  siblingQuote?: T;
  snapshot?: T;
  snapshotHash?: T;
  serviceDescription?: T;
  totalIncVatOre?: T;
  maximumTotalIncVatOre?: T;
  termsVersion?: T;
  validUntil?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  selectedOptionQuote?: T;
  sentAt?: T;
  viewedAt?: T;
  acceptedAt?: T;
  declinedAt?: T;
  declineReason?: T;
  declineComment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  reference?: T;
  quote?: T;
  version?: T;
  supersedes?: T;
  snapshot?: T;
  documentHash?: T;
  termsVersion?: T;
  status?: T;
  signatureEvidence?: T;
  customerSignatureImage?: T;
  signedDocument?: T;
  signedAt?: T;
  companySignatureEvidence?: T;
  companySignatureImage?: T;
  companySignedDocument?: T;
  companySignedAt?: T;
  companySignedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-agreements_select".
 */
export interface ChangeAgreementsSelect<T extends boolean = true> {
  reference?: T;
  workOrder?: T;
  contract?: T;
  version?: T;
  supersedes?: T;
  snapshot?: T;
  documentHash?: T;
  reasonCode?: T;
  reasonDescription?: T;
  beforeTotalIncVatOre?: T;
  afterTotalIncVatOre?: T;
  validUntil?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  sentAt?: T;
  viewedAt?: T;
  acceptanceEvidence?: T;
  acceptedDocument?: T;
  acceptedAt?: T;
  declinedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-terms_select".
 */
export interface ContractTermsSelect<T extends boolean = true> {
  version?: T;
  title?: T;
  contractText?: T;
  withdrawalInstructions?: T;
  withdrawalFormUrl?: T;
  status?: T;
  legalReviewReference?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-orders_select".
 */
export interface WorkOrdersSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  quote?: T;
  contract?: T;
  contractDocumentHash?: T;
  assignedWorker?: T;
  scheduledAt?: T;
  arrivalWindow?: T;
  adminNote?: T;
  customerCancellationRequestedAt?: T;
  cancellationRequestMessage?: T;
  statusBeforeCustomerCancellation?: T;
  customerCancellationResolvedAt?: T;
  customerCancellationResolution?: T;
  status?: T;
  workSummary?: T;
  beforePhotos?: T;
  roofType?: T;
  actualAreaTenths?: T;
  measurementMethod?: T;
  slopeBasis?: T;
  visibleCondition?: T;
  safetyStatus?: T;
  safetyNotes?: T;
  scopeChanged?: T;
  scopeChangeDetails?: T;
  precheckDecision?: T;
  priceOutcome?: T;
  allowedAreaMaxTenths?: T;
  actualSubtotalExVatOre?: T;
  actualVatOre?: T;
  actualTotalIncVatOre?: T;
  blockingReasons?: T;
  approvedChangeAgreement?: T;
  precheckCompletedAt?: T;
  startedAt?: T;
  afterPhotos?: T;
  completionNotes?: T;
  completedAt?: T;
  documentationSubmittedAt?: T;
  completionReviewedBy?: T;
  completionReviewedAt?: T;
  completionReviewNote?: T;
  eventTimeline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-records_select".
 */
export interface InvoiceRecordsSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  workOrder?: T;
  status?: T;
  snapshot?: T;
  documentHash?: T;
  subtotalExVatOre?: T;
  vatOre?: T;
  totalIncVatOre?: T;
  issuedAt?: T;
  dueAt?: T;
  assignedTo?: T;
  externalReference?: T;
  adminNote?: T;
  document?: T;
  approvedAt?: T;
  sentAt?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranties_select".
 */
export interface WarrantiesSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  workOrder?: T;
  status?: T;
  scope?: T;
  startsAt?: T;
  endsAt?: T;
  termsVersion?: T;
  snapshot?: T;
  documentHash?: T;
  document?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-topics_select".
 */
export interface SeoTopicsSelect<T extends boolean = true> {
  fingerprint?: T;
  topic?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  searchIntent?: T;
  service?: T;
  location?: T;
  season?: T;
  source?: T;
  sourceMetrics?: T;
  proposedBrief?: T;
  topicScore?: T;
  overlapScore?: T;
  scoreBreakdown?: T;
  rejectionReasons?:
    | T
    | {
        reason?: T;
        id?: T;
      };
  reasonForSelection?: T;
  status?: T;
  checkedAt?: T;
  relatedPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-runs_select".
 */
export interface SeoRunsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  jobType?: T;
  triggerSource?: T;
  weekKey?: T;
  slot?: T;
  status?: T;
  startedAt?: T;
  finishedAt?: T;
  selectedTopics?: T;
  rejectedTopics?: T;
  modelVersion?: T;
  promptVersion?: T;
  knowledgeVersion?: T;
  qualityResult?: T;
  errorCode?: T;
  errorMessage?: T;
  createdPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  correlationId?: T;
  changedFields?: T;
  beforeHash?: T;
  afterHash?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-jobs_select".
 */
export interface OperationalJobsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  idempotencyKey?: T;
  correlationId?: T;
  attempts?: T;
  maxAttempts?: T;
  availableAt?: T;
  startedAt?: T;
  completedAt?: T;
  lastErrorCode?: T;
  lastErrorMessage?: T;
  payload?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-tokens_select".
 */
export interface AccessTokensSelect<T extends boolean = true> {
  purpose?: T;
  tokenHash?: T;
  subjectType?: T;
  subjectId?: T;
  expiresAt?: T;
  revokedAt?: T;
  usedAt?: T;
  singleUse?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media_select".
 */
export interface PrivateMediaSelect<T extends boolean = true> {
  classification?: T;
  ownerType?: T;
  ownerId?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Edit website contact info, images, prices, and all page texts (NO/EN). Upload photos in Media first, then select them under Images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  phone?: string | null;
  email?: string | null;
  street?: string | null;
  postal?: string | null;
  city?: string | null;
  orgNr?: string | null;
  parentOrg?: string | null;
  navItems?:
    | {
        labelNo: string;
        labelEn: string;
        /**
         * Example: /#tjenester or /personvern
         */
        href: string;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  aboutImage?: (number | null) | Media;
  newRoofImage?: (number | null) | Media;
  heroImageUrl?: string | null;
  aboutImageUrl?: string | null;
  newRoofImageUrl?: string | null;
  testimonialsItems?:
    | {
        quoteNo?: string | null;
        quoteEn?: string | null;
        authorNo?: string | null;
        authorEn?: string | null;
        serviceNo?: string | null;
        serviceEn?: string | null;
        id?: string | null;
      }[]
    | null;
  areaServedNo?: string | null;
  areaServedEn?: string | null;
  openingDays?: string | null;
  openingTime?: string | null;
  closingTime?: string | null;
  calculator?: {
    newRoofPerSqm?: number | null;
    renewalPerSqm?: number | null;
    minSqm?: number | null;
    maxSqm?: number | null;
    defaultSqm?: number | null;
  };
  trust?: {
    sqmRenewed?: string | null;
    warrantyYears?: number | null;
    happyCustomers?: string | null;
    rating?: string | null;
  };
  privacyTitleNo?: string | null;
  privacyTitleEn?: string | null;
  privacyBodyNo?: string | null;
  privacyBodyEn?: string | null;
  privacyLinkNo?: string | null;
  privacyLinkEn?: string | null;
  consentLabelNo?: string | null;
  consentLabelEn?: string | null;
  /**
   * Cron deletes leads and their private photos older than this.
   */
  retentionMonths?: number | null;
  copyMeta?: {
    titleNo?: string | null;
    titleEn?: string | null;
    descriptionNo?: string | null;
    descriptionEn?: string | null;
  };
  copyNav?: {
    homeNo?: string | null;
    homeEn?: string | null;
    servicesNo?: string | null;
    servicesEn?: string | null;
    referencesNo?: string | null;
    referencesEn?: string | null;
    aboutNo?: string | null;
    aboutEn?: string | null;
    productsNo?: string | null;
    productsEn?: string | null;
    contactNo?: string | null;
    contactEn?: string | null;
    contactUsNo?: string | null;
    contactUsEn?: string | null;
    callNo?: string | null;
    callEn?: string | null;
    menuNo?: string | null;
    menuEn?: string | null;
    closeNo?: string | null;
    closeEn?: string | null;
    localeNoNo?: string | null;
    localeNoEn?: string | null;
    localeEnNo?: string | null;
    localeEnEn?: string | null;
  };
  copyHero?: {
    badgeNo?: string | null;
    badgeEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    titleAccentNo?: string | null;
    titleAccentEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
    ctaSecondaryNo?: string | null;
    ctaSecondaryEn?: string | null;
    trustWarrantyNo?: string | null;
    trustWarrantyEn?: string | null;
    trustCustomersNo?: string | null;
    trustCustomersEn?: string | null;
    trustRatingNo?: string | null;
    trustRatingEn?: string | null;
  };
  copySticky?: {
    callNo?: string | null;
    callEn?: string | null;
    bookNo?: string | null;
    bookEn?: string | null;
  };
  copyTrustBar?: {
    itemsNo?: string | null;
    itemsEn?: string | null;
  };
  copyServices?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    showMoreNo?: string | null;
    showMoreEn?: string | null;
    showLessNo?: string | null;
    showLessEn?: string | null;
  };
  copyCalculator?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    hintNo?: string | null;
    hintEn?: string | null;
    sizeLabelNo?: string | null;
    sizeLabelEn?: string | null;
    newRoofNo?: string | null;
    newRoofEn?: string | null;
    renewalNo?: string | null;
    renewalEn?: string | null;
    youSaveNo?: string | null;
    youSaveEn?: string | null;
    cheaperNo?: string | null;
    cheaperEn?: string | null;
    disclaimerNo?: string | null;
    disclaimerEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
  };
  copyReferences?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    noteNo?: string | null;
    noteEn?: string | null;
    beforeNo?: string | null;
    beforeEn?: string | null;
    duringNo?: string | null;
    duringEn?: string | null;
    afterNo?: string | null;
    afterEn?: string | null;
    comparisonHintNo?: string | null;
    comparisonHintEn?: string | null;
    swipeNo?: string | null;
    swipeEn?: string | null;
  };
  copyProducts?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    footerNo?: string | null;
    footerEn?: string | null;
  };
  copyFaq?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
  };
  copyTestimonials?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    itemsNo?: string | null;
    itemsEn?: string | null;
  };
  copyNewRoof?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    bodyNo?: string | null;
    bodyEn?: string | null;
    typesTitleNo?: string | null;
    typesTitleEn?: string | null;
    typesNo?: string | null;
    typesEn?: string | null;
    noteNo?: string | null;
    noteEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
  };
  copyAbout?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    p1No?: string | null;
    p1En?: string | null;
    p2No?: string | null;
    p2En?: string | null;
    p3No?: string | null;
    p3En?: string | null;
    parentNo?: string | null;
    parentEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
    stat1TitleNo?: string | null;
    stat1TitleEn?: string | null;
    stat1DescNo?: string | null;
    stat1DescEn?: string | null;
    stat2TitleNo?: string | null;
    stat2TitleEn?: string | null;
    stat2DescNo?: string | null;
    stat2DescEn?: string | null;
    stat3TitleNo?: string | null;
    stat3TitleEn?: string | null;
    stat3DescNo?: string | null;
    stat3DescEn?: string | null;
    stat4TitleNo?: string | null;
    stat4TitleEn?: string | null;
    stat4DescNo?: string | null;
    stat4DescEn?: string | null;
    companyTitleNo?: string | null;
    companyTitleEn?: string | null;
    companyOrgNo?: string | null;
    companyOrgEn?: string | null;
    companyPhoneNo?: string | null;
    companyPhoneEn?: string | null;
    companyEmailNo?: string | null;
    companyEmailEn?: string | null;
    companyAddressNo?: string | null;
    companyAddressEn?: string | null;
  };
  copyContact?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    phoneNo?: string | null;
    phoneEn?: string | null;
    hoursNo?: string | null;
    hoursEn?: string | null;
    emailNo?: string | null;
    emailEn?: string | null;
    replyNo?: string | null;
    replyEn?: string | null;
    officeNo?: string | null;
    officeEn?: string | null;
    formNameNo?: string | null;
    formNameEn?: string | null;
    formEmailNo?: string | null;
    formEmailEn?: string | null;
    formPhoneNo?: string | null;
    formPhoneEn?: string | null;
    formAddressNo?: string | null;
    formAddressEn?: string | null;
    formHouseNumberNo?: string | null;
    formHouseNumberEn?: string | null;
    formPostalNo?: string | null;
    formPostalEn?: string | null;
    formCityNo?: string | null;
    formCityEn?: string | null;
    formTypeNo?: string | null;
    formTypeEn?: string | null;
    formTypeWashNo?: string | null;
    formTypeWashEn?: string | null;
    formTypeImpregnationNo?: string | null;
    formTypeImpregnationEn?: string | null;
    formTypePaintNo?: string | null;
    formTypePaintEn?: string | null;
    formTypeNewNo?: string | null;
    formTypeNewEn?: string | null;
    formTypeUnsureNo?: string | null;
    formTypeUnsureEn?: string | null;
    formRoofSizeNo?: string | null;
    formRoofSizeEn?: string | null;
    formPhotosNo?: string | null;
    formPhotosEn?: string | null;
    formPhotosHintNo?: string | null;
    formPhotosHintEn?: string | null;
    formChoosePhotosNo?: string | null;
    formChoosePhotosEn?: string | null;
    formNoPhotosNo?: string | null;
    formNoPhotosEn?: string | null;
    formPhotosSelectedOneNo?: string | null;
    formPhotosSelectedOneEn?: string | null;
    formPhotosSelectedManyNo?: string | null;
    formPhotosSelectedManyEn?: string | null;
    formPhotosTooManyNo?: string | null;
    formPhotosTooManyEn?: string | null;
    formPhotosLimitInlineNo?: string | null;
    formPhotosLimitInlineEn?: string | null;
    formPhotoTooLargeNo?: string | null;
    formPhotoTooLargeEn?: string | null;
    formPhotoUploadingNo?: string | null;
    formPhotoUploadingEn?: string | null;
    formPhotoQueuedNo?: string | null;
    formPhotoQueuedEn?: string | null;
    formPhotoReadyNo?: string | null;
    formPhotoReadyEn?: string | null;
    formPhotoFailedNo?: string | null;
    formPhotoFailedEn?: string | null;
    formRoofSizeInvalidNo?: string | null;
    formRoofSizeInvalidEn?: string | null;
    formPartialUploadNo?: string | null;
    formPartialUploadEn?: string | null;
    formSecurityRequiredNo?: string | null;
    formSecurityRequiredEn?: string | null;
    formPrivacyRequiredNo?: string | null;
    formPrivacyRequiredEn?: string | null;
    formMessageNo?: string | null;
    formMessageEn?: string | null;
    formNextNo?: string | null;
    formNextEn?: string | null;
    formBackNo?: string | null;
    formBackEn?: string | null;
    formStepNo?: string | null;
    formStepEn?: string | null;
    formSubmitNo?: string | null;
    formSubmitEn?: string | null;
    formSendingNo?: string | null;
    formSendingEn?: string | null;
    formSuccessNo?: string | null;
    formSuccessEn?: string | null;
    formErrorNo?: string | null;
    formErrorEn?: string | null;
    formRequiredNo?: string | null;
    formRequiredEn?: string | null;
    formInvalidEmailNo?: string | null;
    formInvalidEmailEn?: string | null;
  };
  copyFooter?: {
    taglineNo?: string | null;
    taglineEn?: string | null;
    partOfNo?: string | null;
    partOfEn?: string | null;
    quickLinksNo?: string | null;
    quickLinksEn?: string | null;
    contactNo?: string | null;
    contactEn?: string | null;
    orgLabelNo?: string | null;
    orgLabelEn?: string | null;
    warrantyNoteNo?: string | null;
    warrantyNoteEn?: string | null;
    rightsNo?: string | null;
    rightsEn?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  phone?: T;
  email?: T;
  street?: T;
  postal?: T;
  city?: T;
  orgNr?: T;
  parentOrg?: T;
  navItems?:
    | T
    | {
        labelNo?: T;
        labelEn?: T;
        href?: T;
        visible?: T;
        id?: T;
      };
  logo?: T;
  heroImage?: T;
  aboutImage?: T;
  newRoofImage?: T;
  heroImageUrl?: T;
  aboutImageUrl?: T;
  newRoofImageUrl?: T;
  testimonialsItems?:
    | T
    | {
        quoteNo?: T;
        quoteEn?: T;
        authorNo?: T;
        authorEn?: T;
        serviceNo?: T;
        serviceEn?: T;
        id?: T;
      };
  areaServedNo?: T;
  areaServedEn?: T;
  openingDays?: T;
  openingTime?: T;
  closingTime?: T;
  calculator?:
    | T
    | {
        newRoofPerSqm?: T;
        renewalPerSqm?: T;
        minSqm?: T;
        maxSqm?: T;
        defaultSqm?: T;
      };
  trust?:
    | T
    | {
        sqmRenewed?: T;
        warrantyYears?: T;
        happyCustomers?: T;
        rating?: T;
      };
  privacyTitleNo?: T;
  privacyTitleEn?: T;
  privacyBodyNo?: T;
  privacyBodyEn?: T;
  privacyLinkNo?: T;
  privacyLinkEn?: T;
  consentLabelNo?: T;
  consentLabelEn?: T;
  retentionMonths?: T;
  copyMeta?:
    | T
    | {
        titleNo?: T;
        titleEn?: T;
        descriptionNo?: T;
        descriptionEn?: T;
      };
  copyNav?:
    | T
    | {
        homeNo?: T;
        homeEn?: T;
        servicesNo?: T;
        servicesEn?: T;
        referencesNo?: T;
        referencesEn?: T;
        aboutNo?: T;
        aboutEn?: T;
        productsNo?: T;
        productsEn?: T;
        contactNo?: T;
        contactEn?: T;
        contactUsNo?: T;
        contactUsEn?: T;
        callNo?: T;
        callEn?: T;
        menuNo?: T;
        menuEn?: T;
        closeNo?: T;
        closeEn?: T;
        localeNoNo?: T;
        localeNoEn?: T;
        localeEnNo?: T;
        localeEnEn?: T;
      };
  copyHero?:
    | T
    | {
        badgeNo?: T;
        badgeEn?: T;
        titleNo?: T;
        titleEn?: T;
        titleAccentNo?: T;
        titleAccentEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        ctaNo?: T;
        ctaEn?: T;
        ctaSecondaryNo?: T;
        ctaSecondaryEn?: T;
        trustWarrantyNo?: T;
        trustWarrantyEn?: T;
        trustCustomersNo?: T;
        trustCustomersEn?: T;
        trustRatingNo?: T;
        trustRatingEn?: T;
      };
  copySticky?:
    | T
    | {
        callNo?: T;
        callEn?: T;
        bookNo?: T;
        bookEn?: T;
      };
  copyTrustBar?:
    | T
    | {
        itemsNo?: T;
        itemsEn?: T;
      };
  copyServices?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        showMoreNo?: T;
        showMoreEn?: T;
        showLessNo?: T;
        showLessEn?: T;
      };
  copyCalculator?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        hintNo?: T;
        hintEn?: T;
        sizeLabelNo?: T;
        sizeLabelEn?: T;
        newRoofNo?: T;
        newRoofEn?: T;
        renewalNo?: T;
        renewalEn?: T;
        youSaveNo?: T;
        youSaveEn?: T;
        cheaperNo?: T;
        cheaperEn?: T;
        disclaimerNo?: T;
        disclaimerEn?: T;
        ctaNo?: T;
        ctaEn?: T;
      };
  copyReferences?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        noteNo?: T;
        noteEn?: T;
        beforeNo?: T;
        beforeEn?: T;
        duringNo?: T;
        duringEn?: T;
        afterNo?: T;
        afterEn?: T;
        comparisonHintNo?: T;
        comparisonHintEn?: T;
        swipeNo?: T;
        swipeEn?: T;
      };
  copyProducts?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        footerNo?: T;
        footerEn?: T;
      };
  copyFaq?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
      };
  copyTestimonials?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        itemsNo?: T;
        itemsEn?: T;
      };
  copyNewRoof?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        bodyNo?: T;
        bodyEn?: T;
        typesTitleNo?: T;
        typesTitleEn?: T;
        typesNo?: T;
        typesEn?: T;
        noteNo?: T;
        noteEn?: T;
        ctaNo?: T;
        ctaEn?: T;
      };
  copyAbout?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        p1No?: T;
        p1En?: T;
        p2No?: T;
        p2En?: T;
        p3No?: T;
        p3En?: T;
        parentNo?: T;
        parentEn?: T;
        ctaNo?: T;
        ctaEn?: T;
        stat1TitleNo?: T;
        stat1TitleEn?: T;
        stat1DescNo?: T;
        stat1DescEn?: T;
        stat2TitleNo?: T;
        stat2TitleEn?: T;
        stat2DescNo?: T;
        stat2DescEn?: T;
        stat3TitleNo?: T;
        stat3TitleEn?: T;
        stat3DescNo?: T;
        stat3DescEn?: T;
        stat4TitleNo?: T;
        stat4TitleEn?: T;
        stat4DescNo?: T;
        stat4DescEn?: T;
        companyTitleNo?: T;
        companyTitleEn?: T;
        companyOrgNo?: T;
        companyOrgEn?: T;
        companyPhoneNo?: T;
        companyPhoneEn?: T;
        companyEmailNo?: T;
        companyEmailEn?: T;
        companyAddressNo?: T;
        companyAddressEn?: T;
      };
  copyContact?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        phoneNo?: T;
        phoneEn?: T;
        hoursNo?: T;
        hoursEn?: T;
        emailNo?: T;
        emailEn?: T;
        replyNo?: T;
        replyEn?: T;
        officeNo?: T;
        officeEn?: T;
        formNameNo?: T;
        formNameEn?: T;
        formEmailNo?: T;
        formEmailEn?: T;
        formPhoneNo?: T;
        formPhoneEn?: T;
        formAddressNo?: T;
        formAddressEn?: T;
        formHouseNumberNo?: T;
        formHouseNumberEn?: T;
        formPostalNo?: T;
        formPostalEn?: T;
        formCityNo?: T;
        formCityEn?: T;
        formTypeNo?: T;
        formTypeEn?: T;
        formTypeWashNo?: T;
        formTypeWashEn?: T;
        formTypeImpregnationNo?: T;
        formTypeImpregnationEn?: T;
        formTypePaintNo?: T;
        formTypePaintEn?: T;
        formTypeNewNo?: T;
        formTypeNewEn?: T;
        formTypeUnsureNo?: T;
        formTypeUnsureEn?: T;
        formRoofSizeNo?: T;
        formRoofSizeEn?: T;
        formPhotosNo?: T;
        formPhotosEn?: T;
        formPhotosHintNo?: T;
        formPhotosHintEn?: T;
        formChoosePhotosNo?: T;
        formChoosePhotosEn?: T;
        formNoPhotosNo?: T;
        formNoPhotosEn?: T;
        formPhotosSelectedOneNo?: T;
        formPhotosSelectedOneEn?: T;
        formPhotosSelectedManyNo?: T;
        formPhotosSelectedManyEn?: T;
        formPhotosTooManyNo?: T;
        formPhotosTooManyEn?: T;
        formPhotosLimitInlineNo?: T;
        formPhotosLimitInlineEn?: T;
        formPhotoTooLargeNo?: T;
        formPhotoTooLargeEn?: T;
        formPhotoUploadingNo?: T;
        formPhotoUploadingEn?: T;
        formPhotoQueuedNo?: T;
        formPhotoQueuedEn?: T;
        formPhotoReadyNo?: T;
        formPhotoReadyEn?: T;
        formPhotoFailedNo?: T;
        formPhotoFailedEn?: T;
        formRoofSizeInvalidNo?: T;
        formRoofSizeInvalidEn?: T;
        formPartialUploadNo?: T;
        formPartialUploadEn?: T;
        formSecurityRequiredNo?: T;
        formSecurityRequiredEn?: T;
        formPrivacyRequiredNo?: T;
        formPrivacyRequiredEn?: T;
        formMessageNo?: T;
        formMessageEn?: T;
        formNextNo?: T;
        formNextEn?: T;
        formBackNo?: T;
        formBackEn?: T;
        formStepNo?: T;
        formStepEn?: T;
        formSubmitNo?: T;
        formSubmitEn?: T;
        formSendingNo?: T;
        formSendingEn?: T;
        formSuccessNo?: T;
        formSuccessEn?: T;
        formErrorNo?: T;
        formErrorEn?: T;
        formRequiredNo?: T;
        formRequiredEn?: T;
        formInvalidEmailNo?: T;
        formInvalidEmailEn?: T;
      };
  copyFooter?:
    | T
    | {
        taglineNo?: T;
        taglineEn?: T;
        partOfNo?: T;
        partOfEn?: T;
        quickLinksNo?: T;
        quickLinksEn?: T;
        contactNo?: T;
        contactEn?: T;
        orgLabelNo?: T;
        orgLabelEn?: T;
        warrantyNoteNo?: T;
        warrantyNoteEn?: T;
        rightsNo?: T;
        rightsEn?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}