/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    products: Product;
    faq: Faq;
    pages: Page;
    posts: Post;
    redirects: Redirect;
    leads: Lead;
    'work-orders': WorkOrder;
    'seo-topics': SeoTopic;
    'seo-runs': SeoRun;
    'audit-events': AuditEvent;
    'operational-jobs': OperationalJob;
    'access-tokens': AccessToken;
    'private-media': PrivateMedia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'work-orders': WorkOrdersSelect<false> | WorkOrdersSelect<true>;
    'seo-topics': SeoTopicsSelect<false> | SeoTopicsSelect<true>;
    'seo-runs': SeoRunsSelect<false> | SeoRunsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'operational-jobs': OperationalJobsSelect<false> | OperationalJobsSelect<true>;
    'access-tokens': AccessTokensSelect<false> | AccessTokensSelect<true>;
    'private-media': PrivateMediaSelect<false> | PrivateMediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Opprett egne kontoer for ansatte. Deaktivering avslutter aktive sesjoner.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Navnet som vises i arbeidsoversikten.
   */
  displayName?: string | null;
  phone?: string | null;
  role: 'admin' | 'worker';
  /**
   * Slå av for å stanse innlogging og tilbakekalle aktive sesjoner.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload images here (stored on Vercel Blob). Then pick them in Site Settings or Project stages. Prefer WebP when possible; large JPEG/PNG are auto-converted when supported.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description for accessibility / SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  key: string;
  titleNo: string;
  titleEn: string;
  descriptionNo: string;
  descriptionEn: string;
  icon?: ('check' | 'shield' | 'droplets' | 'paint' | 'home' | 'wrench' | 'sparkles') | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  titleNo: string;
  titleEn: string;
  order?: number | null;
  stages?:
    | {
        label: 'before' | 'during' | 'after';
        captionNo: string;
        captionEn: string;
        /**
         * Upload via Media library (Vercel Blob). Preferred.
         */
        image?: (number | null) | Media;
        /**
         * Used only if no uploaded image is selected
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  categoryNo: string;
  categoryEn: string;
  descriptionNo: string;
  descriptionEn: string;
  image?: (number | null) | Media;
  badgesNo?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  badgesEn?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  questionNo: string;
  questionEn: string;
  answerNo: string;
  answerEn: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Lowercase URL segment. “blogg” and “personvern” are reserved.
   */
  slug: string;
  titleNo: string;
  titleEn: string;
  excerptNo?: string | null;
  excerptEn?: string | null;
  /**
   * Plain text with optional Markdown-style ## headings and - lists.
   */
  contentNo: string;
  /**
   * Plain text with optional Markdown-style ## headings and - lists.
   */
  contentEn: string;
  seoTitleNo?: string | null;
  seoTitleEn?: string | null;
  seoDescriptionNo?: string | null;
  seoDescriptionEn?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Lowercase URL segment below /blogg.
   */
  slug: string;
  titleNo: string;
  titleEn?: string | null;
  excerptNo?: string | null;
  excerptEn?: string | null;
  /**
   * Safe Markdown: ## headings, lists, **bold** and [link text](https://...). HTML is not rendered.
   */
  contentNo: string;
  /**
   * Leave empty until a complete English version has been reviewed.
   */
  contentEn?: string | null;
  heroImage?: (number | null) | Media;
  seoTitleNo?: string | null;
  seoTitleEn?: string | null;
  seoDescriptionNo?: string | null;
  seoDescriptionEn?: string | null;
  publishedAt?: string | null;
  editorialStatus: 'draft' | 'ai_qa' | 'human_review' | 'approved' | 'scheduled' | 'published';
  /**
   * Kan bare lagres når redaksjonell status er Godkjent.
   */
  scheduledAt?: string | null;
  searchIntent?: ('informational' | 'commercial' | 'local' | 'comparison') | null;
  primaryKeyword?: string | null;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  primaryService?: (number | null) | Service;
  locationText?: string | null;
  category?: string | null;
  sources?:
    | {
        label: string;
        url: string;
        publisher?: string | null;
        accessedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  authorName?: string | null;
  reviewerName?: string | null;
  reviewedAt?: string | null;
  aiAssisted?: boolean | null;
  aiGenerationRun?: (number | null) | SeoRun;
  qualityScore?: number | null;
  relatedPosts?: (number | Post)[] | null;
  relatedServices?: (number | Service)[] | null;
  ctaVariant?: ('assessment' | 'wash' | 'renewal' | 'new_roof') | null;
  faqItems?:
    | {
        questionNo: string;
        answerNo: string;
        questionEn?: string | null;
        answerEn?: string | null;
        id?: string | null;
      }[]
    | null;
  lastContentAuditAt?: string | null;
  performanceNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ikke-sensitive spor for temavalg, utkast og kvalitetssjekk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-runs".
 */
export interface SeoRun {
  id: number;
  jobType: string;
  status: 'running' | 'completed' | 'failed' | 'attention';
  startedAt: string;
  finishedAt?: string | null;
  selectedTopics?: (number | SeoTopic)[] | null;
  rejectedTopics?: (number | SeoTopic)[] | null;
  modelVersion?: string | null;
  promptVersion?: string | null;
  knowledgeVersion?: string | null;
  qualityResult?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errorCode?: string | null;
  /**
   * Sanitert feiltekst uten prompts, nøkler eller kundedata.
   */
  errorMessage?: string | null;
  createdPost?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-topics".
 */
export interface SeoTopic {
  id: number;
  topic: string;
  primaryKeyword: string;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  searchIntent: 'informational' | 'commercial' | 'local' | 'comparison';
  service?: (number | null) | Service;
  location?: string | null;
  season?: string | null;
  source: 'search_console' | 'ads' | 'trends' | 'lead' | 'manual';
  /**
   * Kun aggregerte tall; aldri kundedata eller tokens.
   */
  sourceMetrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  topicScore: number;
  overlapScore: number;
  reasonForSelection: string;
  status: 'candidate' | 'rejected' | 'queued' | 'drafted' | 'approved' | 'published';
  checkedAt?: string | null;
  relatedPost?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redirects are currently resolved for CMS page slugs and blog post routes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Locale-specific (/no/gammel) or locale-neutral (/gammel) source path.
   */
  fromPath: string;
  /**
   * Internal destination beginning with /.
   */
  toPath?: string | null;
  toUrl?: string | null;
  /**
   * Permanent redirects use HTTP 308; temporary ones use 307.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email?: string | null;
  phone?: string | null;
  address: string;
  houseNumber?: string | null;
  postal: string;
  city?: string | null;
  approxSqm?: number | null;
  /**
   * Lead photos from the website form. Previews work in admin; direct Blob links are private.
   */
  photoUrls?: string | null;
  inquiryType:
    | 'takvask'
    | 'takvask_impregnering'
    | 'impregnering'
    | 'takmaling'
    | 'nytt_tak'
    | 'usikker'
    | 'vedlikehold'
    | 'kledning';
  message?: string | null;
  language: 'no' | 'en';
  status?: ('new' | 'contacted' | 'qualified' | 'closed') | null;
  /**
   * When the visitor accepted the privacy consent checkbox.
   */
  consentAt?: string | null;
  /**
   * Exact consent label shown at submit time.
   */
  consentText?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  gclid?: string | null;
  gbraid?: string | null;
  wbraid?: string | null;
  fbclid?: string | null;
  msclkid?: string | null;
  landingPage?: string | null;
  /**
   * Last blog article CTA used before this inquiry.
   */
  contentSourcePath?: string | null;
  referrer?: string | null;
  marketingConsent?: ('granted' | 'denied' | 'unknown') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Grunnskall for tildelte oppdrag. Arbeidsflyt og dokumentasjon utvides i arbeidsordrefasen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-orders".
 */
export interface WorkOrder {
  id: number;
  reference: string;
  lead?: (number | null) | Lead;
  assignedWorker?: (number | null) | User;
  scheduledAt?: string | null;
  status: 'unassigned' | 'assigned' | 'scheduled';
  workSummary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable operational audit trail. Sensitive values and raw customer data must not be stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor?: (number | null) | User;
  action: string;
  entityType: string;
  entityId: string;
  correlationId: string;
  /**
   * Field names only; never raw before/after values.
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  beforeHash?: string | null;
  afterHash?: string | null;
  /**
   * Allow-listed operational identifiers only. No names, addresses, contact details, secrets or tokens.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Retryable jobs and outbox operations. Payload must contain IDs, not raw customer data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-jobs".
 */
export interface OperationalJob {
  id: number;
  type: string;
  status: 'pending' | 'running' | 'retry' | 'completed' | 'failed' | 'attention' | 'cancelled';
  idempotencyKey: string;
  correlationId: string;
  attempts: number;
  maxAttempts: number;
  availableAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  lastErrorCode?: string | null;
  /**
   * Sanitized operational message; no raw payload.
   */
  lastErrorMessage?: string | null;
  /**
   * References and non-sensitive job options only. Do not copy lead data here.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hashed tokens for customer links. Plain-text tokens are never persisted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-tokens".
 */
export interface AccessToken {
  id: number;
  purpose: string;
  tokenHash: string;
  subjectType: string;
  subjectId: string;
  expiresAt: string;
  revokedAt?: string | null;
  usedAt?: string | null;
  singleUse?: boolean | null;
  /**
   * Non-sensitive operational metadata only. Never store the plain token.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer, contract and work files. Access must always be authorized server-side.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media".
 */
export interface PrivateMedia {
  id: number;
  classification: 'customer' | 'measurement' | 'contract' | 'work';
  ownerType?: string | null;
  ownerId?: string | null;
  /**
   * Required when the file is an image shown in UI.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'work-orders';
        value: number | WorkOrder;
      } | null)
    | ({
        relationTo: 'seo-topics';
        value: number | SeoTopic;
      } | null)
    | ({
        relationTo: 'seo-runs';
        value: number | SeoRun;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'operational-jobs';
        value: number | OperationalJob;
      } | null)
    | ({
        relationTo: 'access-tokens';
        value: number | AccessToken;
      } | null)
    | ({
        relationTo: 'private-media';
        value: number | PrivateMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  phone?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  key?: T;
  titleNo?: T;
  titleEn?: T;
  descriptionNo?: T;
  descriptionEn?: T;
  icon?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  titleNo?: T;
  titleEn?: T;
  order?: T;
  stages?:
    | T
    | {
        label?: T;
        captionNo?: T;
        captionEn?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  categoryNo?: T;
  categoryEn?: T;
  descriptionNo?: T;
  descriptionEn?: T;
  image?: T;
  badgesNo?:
    | T
    | {
        label?: T;
        id?: T;
      };
  badgesEn?:
    | T
    | {
        label?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  questionNo?: T;
  questionEn?: T;
  answerNo?: T;
  answerEn?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  titleNo?: T;
  titleEn?: T;
  excerptNo?: T;
  excerptEn?: T;
  contentNo?: T;
  contentEn?: T;
  seoTitleNo?: T;
  seoTitleEn?: T;
  seoDescriptionNo?: T;
  seoDescriptionEn?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  titleNo?: T;
  titleEn?: T;
  excerptNo?: T;
  excerptEn?: T;
  contentNo?: T;
  contentEn?: T;
  heroImage?: T;
  seoTitleNo?: T;
  seoTitleEn?: T;
  seoDescriptionNo?: T;
  seoDescriptionEn?: T;
  publishedAt?: T;
  editorialStatus?: T;
  scheduledAt?: T;
  searchIntent?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  primaryService?: T;
  locationText?: T;
  category?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        publisher?: T;
        accessedAt?: T;
        id?: T;
      };
  authorName?: T;
  reviewerName?: T;
  reviewedAt?: T;
  aiAssisted?: T;
  aiGenerationRun?: T;
  qualityScore?: T;
  relatedPosts?: T;
  relatedServices?: T;
  ctaVariant?: T;
  faqItems?:
    | T
    | {
        questionNo?: T;
        answerNo?: T;
        questionEn?: T;
        answerEn?: T;
        id?: T;
      };
  lastContentAuditAt?: T;
  performanceNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  toUrl?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  address?: T;
  houseNumber?: T;
  postal?: T;
  city?: T;
  approxSqm?: T;
  photoUrls?: T;
  inquiryType?: T;
  message?: T;
  language?: T;
  status?: T;
  consentAt?: T;
  consentText?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  utmTerm?: T;
  gclid?: T;
  gbraid?: T;
  wbraid?: T;
  fbclid?: T;
  msclkid?: T;
  landingPage?: T;
  contentSourcePath?: T;
  referrer?: T;
  marketingConsent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-orders_select".
 */
export interface WorkOrdersSelect<T extends boolean = true> {
  reference?: T;
  lead?: T;
  assignedWorker?: T;
  scheduledAt?: T;
  status?: T;
  workSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-topics_select".
 */
export interface SeoTopicsSelect<T extends boolean = true> {
  topic?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  searchIntent?: T;
  service?: T;
  location?: T;
  season?: T;
  source?: T;
  sourceMetrics?: T;
  topicScore?: T;
  overlapScore?: T;
  reasonForSelection?: T;
  status?: T;
  checkedAt?: T;
  relatedPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-runs_select".
 */
export interface SeoRunsSelect<T extends boolean = true> {
  jobType?: T;
  status?: T;
  startedAt?: T;
  finishedAt?: T;
  selectedTopics?: T;
  rejectedTopics?: T;
  modelVersion?: T;
  promptVersion?: T;
  knowledgeVersion?: T;
  qualityResult?: T;
  errorCode?: T;
  errorMessage?: T;
  createdPost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  correlationId?: T;
  changedFields?: T;
  beforeHash?: T;
  afterHash?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-jobs_select".
 */
export interface OperationalJobsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  idempotencyKey?: T;
  correlationId?: T;
  attempts?: T;
  maxAttempts?: T;
  availableAt?: T;
  startedAt?: T;
  completedAt?: T;
  lastErrorCode?: T;
  lastErrorMessage?: T;
  payload?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-tokens_select".
 */
export interface AccessTokensSelect<T extends boolean = true> {
  purpose?: T;
  tokenHash?: T;
  subjectType?: T;
  subjectId?: T;
  expiresAt?: T;
  revokedAt?: T;
  usedAt?: T;
  singleUse?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-media_select".
 */
export interface PrivateMediaSelect<T extends boolean = true> {
  classification?: T;
  ownerType?: T;
  ownerId?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Edit website contact info, images, prices, and all page texts (NO/EN). Upload photos in Media first, then select them under Images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  phone?: string | null;
  email?: string | null;
  street?: string | null;
  postal?: string | null;
  city?: string | null;
  orgNr?: string | null;
  parentOrg?: string | null;
  navItems?:
    | {
        labelNo: string;
        labelEn: string;
        /**
         * Example: /#tjenester or /personvern
         */
        href: string;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  aboutImage?: (number | null) | Media;
  newRoofImage?: (number | null) | Media;
  heroImageUrl?: string | null;
  aboutImageUrl?: string | null;
  newRoofImageUrl?: string | null;
  testimonialsItems?:
    | {
        quoteNo?: string | null;
        quoteEn?: string | null;
        authorNo?: string | null;
        authorEn?: string | null;
        serviceNo?: string | null;
        serviceEn?: string | null;
        id?: string | null;
      }[]
    | null;
  areaServedNo?: string | null;
  areaServedEn?: string | null;
  openingDays?: string | null;
  openingTime?: string | null;
  closingTime?: string | null;
  calculator?: {
    newRoofPerSqm?: number | null;
    renewalPerSqm?: number | null;
    minSqm?: number | null;
    maxSqm?: number | null;
    defaultSqm?: number | null;
  };
  trust?: {
    sqmRenewed?: string | null;
    warrantyYears?: number | null;
    happyCustomers?: string | null;
    rating?: string | null;
  };
  privacyTitleNo?: string | null;
  privacyTitleEn?: string | null;
  privacyBodyNo?: string | null;
  privacyBodyEn?: string | null;
  privacyLinkNo?: string | null;
  privacyLinkEn?: string | null;
  consentLabelNo?: string | null;
  consentLabelEn?: string | null;
  /**
   * Cron deletes leads and their private photos older than this.
   */
  retentionMonths?: number | null;
  copyMeta?: {
    titleNo?: string | null;
    titleEn?: string | null;
    descriptionNo?: string | null;
    descriptionEn?: string | null;
  };
  copyNav?: {
    homeNo?: string | null;
    homeEn?: string | null;
    servicesNo?: string | null;
    servicesEn?: string | null;
    referencesNo?: string | null;
    referencesEn?: string | null;
    aboutNo?: string | null;
    aboutEn?: string | null;
    productsNo?: string | null;
    productsEn?: string | null;
    contactNo?: string | null;
    contactEn?: string | null;
    contactUsNo?: string | null;
    contactUsEn?: string | null;
    callNo?: string | null;
    callEn?: string | null;
    menuNo?: string | null;
    menuEn?: string | null;
    closeNo?: string | null;
    closeEn?: string | null;
    localeNoNo?: string | null;
    localeNoEn?: string | null;
    localeEnNo?: string | null;
    localeEnEn?: string | null;
  };
  copyHero?: {
    badgeNo?: string | null;
    badgeEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    titleAccentNo?: string | null;
    titleAccentEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
    ctaSecondaryNo?: string | null;
    ctaSecondaryEn?: string | null;
    trustWarrantyNo?: string | null;
    trustWarrantyEn?: string | null;
    trustCustomersNo?: string | null;
    trustCustomersEn?: string | null;
    trustRatingNo?: string | null;
    trustRatingEn?: string | null;
  };
  copySticky?: {
    callNo?: string | null;
    callEn?: string | null;
    bookNo?: string | null;
    bookEn?: string | null;
  };
  copyTrustBar?: {
    itemsNo?: string | null;
    itemsEn?: string | null;
  };
  copyServices?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    showMoreNo?: string | null;
    showMoreEn?: string | null;
    showLessNo?: string | null;
    showLessEn?: string | null;
  };
  copyCalculator?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    hintNo?: string | null;
    hintEn?: string | null;
    sizeLabelNo?: string | null;
    sizeLabelEn?: string | null;
    newRoofNo?: string | null;
    newRoofEn?: string | null;
    renewalNo?: string | null;
    renewalEn?: string | null;
    youSaveNo?: string | null;
    youSaveEn?: string | null;
    cheaperNo?: string | null;
    cheaperEn?: string | null;
    disclaimerNo?: string | null;
    disclaimerEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
  };
  copyReferences?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    noteNo?: string | null;
    noteEn?: string | null;
    beforeNo?: string | null;
    beforeEn?: string | null;
    duringNo?: string | null;
    duringEn?: string | null;
    afterNo?: string | null;
    afterEn?: string | null;
    comparisonHintNo?: string | null;
    comparisonHintEn?: string | null;
    swipeNo?: string | null;
    swipeEn?: string | null;
  };
  copyProducts?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    footerNo?: string | null;
    footerEn?: string | null;
  };
  copyFaq?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
  };
  copyTestimonials?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    itemsNo?: string | null;
    itemsEn?: string | null;
  };
  copyNewRoof?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    bodyNo?: string | null;
    bodyEn?: string | null;
    typesTitleNo?: string | null;
    typesTitleEn?: string | null;
    typesNo?: string | null;
    typesEn?: string | null;
    noteNo?: string | null;
    noteEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
  };
  copyAbout?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    p1No?: string | null;
    p1En?: string | null;
    p2No?: string | null;
    p2En?: string | null;
    p3No?: string | null;
    p3En?: string | null;
    parentNo?: string | null;
    parentEn?: string | null;
    ctaNo?: string | null;
    ctaEn?: string | null;
    stat1TitleNo?: string | null;
    stat1TitleEn?: string | null;
    stat1DescNo?: string | null;
    stat1DescEn?: string | null;
    stat2TitleNo?: string | null;
    stat2TitleEn?: string | null;
    stat2DescNo?: string | null;
    stat2DescEn?: string | null;
    stat3TitleNo?: string | null;
    stat3TitleEn?: string | null;
    stat3DescNo?: string | null;
    stat3DescEn?: string | null;
    stat4TitleNo?: string | null;
    stat4TitleEn?: string | null;
    stat4DescNo?: string | null;
    stat4DescEn?: string | null;
    companyTitleNo?: string | null;
    companyTitleEn?: string | null;
    companyOrgNo?: string | null;
    companyOrgEn?: string | null;
    companyPhoneNo?: string | null;
    companyPhoneEn?: string | null;
    companyEmailNo?: string | null;
    companyEmailEn?: string | null;
    companyAddressNo?: string | null;
    companyAddressEn?: string | null;
  };
  copyContact?: {
    eyebrowNo?: string | null;
    eyebrowEn?: string | null;
    titleNo?: string | null;
    titleEn?: string | null;
    subtitleNo?: string | null;
    subtitleEn?: string | null;
    phoneNo?: string | null;
    phoneEn?: string | null;
    hoursNo?: string | null;
    hoursEn?: string | null;
    emailNo?: string | null;
    emailEn?: string | null;
    replyNo?: string | null;
    replyEn?: string | null;
    officeNo?: string | null;
    officeEn?: string | null;
    formNameNo?: string | null;
    formNameEn?: string | null;
    formEmailNo?: string | null;
    formEmailEn?: string | null;
    formPhoneNo?: string | null;
    formPhoneEn?: string | null;
    formAddressNo?: string | null;
    formAddressEn?: string | null;
    formHouseNumberNo?: string | null;
    formHouseNumberEn?: string | null;
    formPostalNo?: string | null;
    formPostalEn?: string | null;
    formCityNo?: string | null;
    formCityEn?: string | null;
    formTypeNo?: string | null;
    formTypeEn?: string | null;
    formTypeWashNo?: string | null;
    formTypeWashEn?: string | null;
    formTypeImpregnationNo?: string | null;
    formTypeImpregnationEn?: string | null;
    formTypePaintNo?: string | null;
    formTypePaintEn?: string | null;
    formTypeNewNo?: string | null;
    formTypeNewEn?: string | null;
    formTypeUnsureNo?: string | null;
    formTypeUnsureEn?: string | null;
    formRoofSizeNo?: string | null;
    formRoofSizeEn?: string | null;
    formPhotosNo?: string | null;
    formPhotosEn?: string | null;
    formPhotosHintNo?: string | null;
    formPhotosHintEn?: string | null;
    formChoosePhotosNo?: string | null;
    formChoosePhotosEn?: string | null;
    formNoPhotosNo?: string | null;
    formNoPhotosEn?: string | null;
    formPhotosSelectedOneNo?: string | null;
    formPhotosSelectedOneEn?: string | null;
    formPhotosSelectedManyNo?: string | null;
    formPhotosSelectedManyEn?: string | null;
    formPhotosTooManyNo?: string | null;
    formPhotosTooManyEn?: string | null;
    formPhotosLimitInlineNo?: string | null;
    formPhotosLimitInlineEn?: string | null;
    formPhotoTooLargeNo?: string | null;
    formPhotoTooLargeEn?: string | null;
    formPhotoUploadingNo?: string | null;
    formPhotoUploadingEn?: string | null;
    formPhotoQueuedNo?: string | null;
    formPhotoQueuedEn?: string | null;
    formPhotoReadyNo?: string | null;
    formPhotoReadyEn?: string | null;
    formPhotoFailedNo?: string | null;
    formPhotoFailedEn?: string | null;
    formRoofSizeInvalidNo?: string | null;
    formRoofSizeInvalidEn?: string | null;
    formPartialUploadNo?: string | null;
    formPartialUploadEn?: string | null;
    formSecurityRequiredNo?: string | null;
    formSecurityRequiredEn?: string | null;
    formPrivacyRequiredNo?: string | null;
    formPrivacyRequiredEn?: string | null;
    formMessageNo?: string | null;
    formMessageEn?: string | null;
    formNextNo?: string | null;
    formNextEn?: string | null;
    formBackNo?: string | null;
    formBackEn?: string | null;
    formStepNo?: string | null;
    formStepEn?: string | null;
    formSubmitNo?: string | null;
    formSubmitEn?: string | null;
    formSendingNo?: string | null;
    formSendingEn?: string | null;
    formSuccessNo?: string | null;
    formSuccessEn?: string | null;
    formErrorNo?: string | null;
    formErrorEn?: string | null;
    formRequiredNo?: string | null;
    formRequiredEn?: string | null;
    formInvalidEmailNo?: string | null;
    formInvalidEmailEn?: string | null;
  };
  copyFooter?: {
    taglineNo?: string | null;
    taglineEn?: string | null;
    partOfNo?: string | null;
    partOfEn?: string | null;
    quickLinksNo?: string | null;
    quickLinksEn?: string | null;
    contactNo?: string | null;
    contactEn?: string | null;
    orgLabelNo?: string | null;
    orgLabelEn?: string | null;
    warrantyNoteNo?: string | null;
    warrantyNoteEn?: string | null;
    rightsNo?: string | null;
    rightsEn?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  phone?: T;
  email?: T;
  street?: T;
  postal?: T;
  city?: T;
  orgNr?: T;
  parentOrg?: T;
  navItems?:
    | T
    | {
        labelNo?: T;
        labelEn?: T;
        href?: T;
        visible?: T;
        id?: T;
      };
  logo?: T;
  heroImage?: T;
  aboutImage?: T;
  newRoofImage?: T;
  heroImageUrl?: T;
  aboutImageUrl?: T;
  newRoofImageUrl?: T;
  testimonialsItems?:
    | T
    | {
        quoteNo?: T;
        quoteEn?: T;
        authorNo?: T;
        authorEn?: T;
        serviceNo?: T;
        serviceEn?: T;
        id?: T;
      };
  areaServedNo?: T;
  areaServedEn?: T;
  openingDays?: T;
  openingTime?: T;
  closingTime?: T;
  calculator?:
    | T
    | {
        newRoofPerSqm?: T;
        renewalPerSqm?: T;
        minSqm?: T;
        maxSqm?: T;
        defaultSqm?: T;
      };
  trust?:
    | T
    | {
        sqmRenewed?: T;
        warrantyYears?: T;
        happyCustomers?: T;
        rating?: T;
      };
  privacyTitleNo?: T;
  privacyTitleEn?: T;
  privacyBodyNo?: T;
  privacyBodyEn?: T;
  privacyLinkNo?: T;
  privacyLinkEn?: T;
  consentLabelNo?: T;
  consentLabelEn?: T;
  retentionMonths?: T;
  copyMeta?:
    | T
    | {
        titleNo?: T;
        titleEn?: T;
        descriptionNo?: T;
        descriptionEn?: T;
      };
  copyNav?:
    | T
    | {
        homeNo?: T;
        homeEn?: T;
        servicesNo?: T;
        servicesEn?: T;
        referencesNo?: T;
        referencesEn?: T;
        aboutNo?: T;
        aboutEn?: T;
        productsNo?: T;
        productsEn?: T;
        contactNo?: T;
        contactEn?: T;
        contactUsNo?: T;
        contactUsEn?: T;
        callNo?: T;
        callEn?: T;
        menuNo?: T;
        menuEn?: T;
        closeNo?: T;
        closeEn?: T;
        localeNoNo?: T;
        localeNoEn?: T;
        localeEnNo?: T;
        localeEnEn?: T;
      };
  copyHero?:
    | T
    | {
        badgeNo?: T;
        badgeEn?: T;
        titleNo?: T;
        titleEn?: T;
        titleAccentNo?: T;
        titleAccentEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        ctaNo?: T;
        ctaEn?: T;
        ctaSecondaryNo?: T;
        ctaSecondaryEn?: T;
        trustWarrantyNo?: T;
        trustWarrantyEn?: T;
        trustCustomersNo?: T;
        trustCustomersEn?: T;
        trustRatingNo?: T;
        trustRatingEn?: T;
      };
  copySticky?:
    | T
    | {
        callNo?: T;
        callEn?: T;
        bookNo?: T;
        bookEn?: T;
      };
  copyTrustBar?:
    | T
    | {
        itemsNo?: T;
        itemsEn?: T;
      };
  copyServices?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        showMoreNo?: T;
        showMoreEn?: T;
        showLessNo?: T;
        showLessEn?: T;
      };
  copyCalculator?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        hintNo?: T;
        hintEn?: T;
        sizeLabelNo?: T;
        sizeLabelEn?: T;
        newRoofNo?: T;
        newRoofEn?: T;
        renewalNo?: T;
        renewalEn?: T;
        youSaveNo?: T;
        youSaveEn?: T;
        cheaperNo?: T;
        cheaperEn?: T;
        disclaimerNo?: T;
        disclaimerEn?: T;
        ctaNo?: T;
        ctaEn?: T;
      };
  copyReferences?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        noteNo?: T;
        noteEn?: T;
        beforeNo?: T;
        beforeEn?: T;
        duringNo?: T;
        duringEn?: T;
        afterNo?: T;
        afterEn?: T;
        comparisonHintNo?: T;
        comparisonHintEn?: T;
        swipeNo?: T;
        swipeEn?: T;
      };
  copyProducts?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        footerNo?: T;
        footerEn?: T;
      };
  copyFaq?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
      };
  copyTestimonials?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        itemsNo?: T;
        itemsEn?: T;
      };
  copyNewRoof?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        bodyNo?: T;
        bodyEn?: T;
        typesTitleNo?: T;
        typesTitleEn?: T;
        typesNo?: T;
        typesEn?: T;
        noteNo?: T;
        noteEn?: T;
        ctaNo?: T;
        ctaEn?: T;
      };
  copyAbout?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        p1No?: T;
        p1En?: T;
        p2No?: T;
        p2En?: T;
        p3No?: T;
        p3En?: T;
        parentNo?: T;
        parentEn?: T;
        ctaNo?: T;
        ctaEn?: T;
        stat1TitleNo?: T;
        stat1TitleEn?: T;
        stat1DescNo?: T;
        stat1DescEn?: T;
        stat2TitleNo?: T;
        stat2TitleEn?: T;
        stat2DescNo?: T;
        stat2DescEn?: T;
        stat3TitleNo?: T;
        stat3TitleEn?: T;
        stat3DescNo?: T;
        stat3DescEn?: T;
        stat4TitleNo?: T;
        stat4TitleEn?: T;
        stat4DescNo?: T;
        stat4DescEn?: T;
        companyTitleNo?: T;
        companyTitleEn?: T;
        companyOrgNo?: T;
        companyOrgEn?: T;
        companyPhoneNo?: T;
        companyPhoneEn?: T;
        companyEmailNo?: T;
        companyEmailEn?: T;
        companyAddressNo?: T;
        companyAddressEn?: T;
      };
  copyContact?:
    | T
    | {
        eyebrowNo?: T;
        eyebrowEn?: T;
        titleNo?: T;
        titleEn?: T;
        subtitleNo?: T;
        subtitleEn?: T;
        phoneNo?: T;
        phoneEn?: T;
        hoursNo?: T;
        hoursEn?: T;
        emailNo?: T;
        emailEn?: T;
        replyNo?: T;
        replyEn?: T;
        officeNo?: T;
        officeEn?: T;
        formNameNo?: T;
        formNameEn?: T;
        formEmailNo?: T;
        formEmailEn?: T;
        formPhoneNo?: T;
        formPhoneEn?: T;
        formAddressNo?: T;
        formAddressEn?: T;
        formHouseNumberNo?: T;
        formHouseNumberEn?: T;
        formPostalNo?: T;
        formPostalEn?: T;
        formCityNo?: T;
        formCityEn?: T;
        formTypeNo?: T;
        formTypeEn?: T;
        formTypeWashNo?: T;
        formTypeWashEn?: T;
        formTypeImpregnationNo?: T;
        formTypeImpregnationEn?: T;
        formTypePaintNo?: T;
        formTypePaintEn?: T;
        formTypeNewNo?: T;
        formTypeNewEn?: T;
        formTypeUnsureNo?: T;
        formTypeUnsureEn?: T;
        formRoofSizeNo?: T;
        formRoofSizeEn?: T;
        formPhotosNo?: T;
        formPhotosEn?: T;
        formPhotosHintNo?: T;
        formPhotosHintEn?: T;
        formChoosePhotosNo?: T;
        formChoosePhotosEn?: T;
        formNoPhotosNo?: T;
        formNoPhotosEn?: T;
        formPhotosSelectedOneNo?: T;
        formPhotosSelectedOneEn?: T;
        formPhotosSelectedManyNo?: T;
        formPhotosSelectedManyEn?: T;
        formPhotosTooManyNo?: T;
        formPhotosTooManyEn?: T;
        formPhotosLimitInlineNo?: T;
        formPhotosLimitInlineEn?: T;
        formPhotoTooLargeNo?: T;
        formPhotoTooLargeEn?: T;
        formPhotoUploadingNo?: T;
        formPhotoUploadingEn?: T;
        formPhotoQueuedNo?: T;
        formPhotoQueuedEn?: T;
        formPhotoReadyNo?: T;
        formPhotoReadyEn?: T;
        formPhotoFailedNo?: T;
        formPhotoFailedEn?: T;
        formRoofSizeInvalidNo?: T;
        formRoofSizeInvalidEn?: T;
        formPartialUploadNo?: T;
        formPartialUploadEn?: T;
        formSecurityRequiredNo?: T;
        formSecurityRequiredEn?: T;
        formPrivacyRequiredNo?: T;
        formPrivacyRequiredEn?: T;
        formMessageNo?: T;
        formMessageEn?: T;
        formNextNo?: T;
        formNextEn?: T;
        formBackNo?: T;
        formBackEn?: T;
        formStepNo?: T;
        formStepEn?: T;
        formSubmitNo?: T;
        formSubmitEn?: T;
        formSendingNo?: T;
        formSendingEn?: T;
        formSuccessNo?: T;
        formSuccessEn?: T;
        formErrorNo?: T;
        formErrorEn?: T;
        formRequiredNo?: T;
        formRequiredEn?: T;
        formInvalidEmailNo?: T;
        formInvalidEmailEn?: T;
      };
  copyFooter?:
    | T
    | {
        taglineNo?: T;
        taglineEn?: T;
        partOfNo?: T;
        partOfEn?: T;
        quickLinksNo?: T;
        quickLinksEn?: T;
        contactNo?: T;
        contactEn?: T;
        orgLabelNo?: T;
        orgLabelEn?: T;
        warrantyNoteNo?: T;
        warrantyNoteEn?: T;
        rightsNo?: T;
        rightsEn?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}