"use client";

import { useState } from "react";
import type { ChangeAgreementSnapshot } from "@/lib/change-agreements/document";

const nok = (ore: number) => (ore / 100).toLocaleString("nb-NO", { style: "currency", currency: "NOK" });

export function CustomerChange({ token, initial }: { token: string; initial: { status: string; snapshot: ChangeAgreementSnapshot; documentHash: string; customerName: string } }) {
  const [status, setStatus] = useState(initial.status); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function submit(body: Record<string, unknown>) { setBusy(true); setNotice(""); try { const response = await fetch(`/api/customer/change/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string; status?: string }; if (!response.ok) throw new Error(result.error || "Svaret kunne ikke registreres"); if (result.status) setStatus(result.status); setNotice("Svaret er registrert."); } catch (error) { setNotice(error instanceof Error ? error.message : "Svaret kunne ikke registreres"); } finally { setBusy(false); } }
  const done = status === "accepted" || status === "declined";
  return <main className="mx-auto min-h-screen max-w-3xl px-4 py-10 text-foreground"><section className="rounded-3xl border border-white/10 bg-background-elevated p-5 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent">Takfornyelse</p><h1 className="mt-2 text-3xl font-bold">Endringsavtale {initial.snapshot.reference}</h1><p className="mt-3 text-muted-foreground">Berørt arbeid er satt på pause til avtalen er skriftlig godkjent.</p><div className="mt-6 rounded-2xl bg-white/5 p-5"><h2 className="font-bold">Årsak</h2><p className="mt-2">{initial.snapshot.reasonDescription}</p></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Box label="Tidligere pris" value={nok(initial.snapshot.before.totalIncVatOre)} /><Box label="Ny pris inkl. mva." value={nok(initial.snapshot.after.totalIncVatOre)} /><Box label="Tidligere beregnet areal" value={`${initial.snapshot.before.areaTenths / 10} m²`} /><Box label="Kontrollmålt areal" value={`${initial.snapshot.after.areaTenths / 10} m²`} /></dl><a className="mt-5 inline-flex min-h-12 items-center rounded-xl border border-white/15 px-4 font-semibold" href={`/api/customer/change/${token}/pdf`} target="_blank">Åpne PDF</a>{done ? <p className="mt-6 rounded-xl bg-white/5 p-4 font-semibold">Status: {status === "accepted" ? "Akseptert" : "Avslått"}</p> : <form action={async (form) => { await submit({ action: "accept", customerName: form.get("customerName"), expectedDocumentHash: initial.documentHash, accepted: form.get("accepted") === "on" }); }} className="mt-6 grid gap-4"><label className="grid gap-1 font-semibold">Navn<input className="min-h-12 rounded-xl border border-white/15 bg-background px-3" defaultValue={initial.customerName} maxLength={160} name="customerName" required /></label><label className="flex gap-3 rounded-xl border border-white/15 p-4"><input className="mt-1 size-5 shrink-0" name="accepted" required type="checkbox" /><span>Jeg godtar skriftlig endringsavtalen, det nye arbeidsomfanget og den nye prisen inkl. mva.</span></label><button className="min-h-12 rounded-xl bg-accent px-5 font-bold text-accent-foreground disabled:opacity-50" disabled={busy} type="submit">Godta endringsavtalen</button><button className="min-h-12 rounded-xl border border-white/15 px-5 font-semibold disabled:opacity-50" disabled={busy} onClick={() => submit({ action: "decline" })} type="button">Avslå</button></form>}{notice ? <p className="mt-4" role="status">{notice}</p> : null}</section></main>;
}
function Box({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 p-4"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-1 text-xl font-bold">{value}</dd></div>; }
