import type {
  AdminNextCaseWorkspaceAdapter,
  AdminNextCaseWorkspaceView,
} from "@/lib/admin-next/case-workspace-contract";
import {
  ADMIN_NEXT_RF_ROUTE_VERSION,
  buildAdminNextRfRoute,
} from "@/lib/admin-next/rf-route-contract";

const fixtureRfRoute = buildAdminNextRfRoute({
  version: ADMIN_NEXT_RF_ROUTE_VERSION,
  mode: "review",
  case: { id: 1042, reference: "TF-1042", revision: 12 },
  measurement: { id: "R4-2026-1042", revision: 7 },
  snapshot: {
    id: "R4-2026-1042",
    revision: 7,
    hash: "a".repeat(64),
  },
  blocker: "measurement.review_required",
  evidence: ["EVD-R4-1042-01"],
  returnTo:
    "/admin-next-preview/cases/TF-1042?tab=evidence#case-evidence-title",
});

export const adminNextCaseWorkspaceFixture: AdminNextCaseWorkspaceView = {
  reference: "TF-1042",
  customer: "Demo · Kari Nilsen",
  address: "Testveien 12, 0164 Oslo",
  service: "Takfornyelse",
  status: "attention",
  owner: {
    name: "Marius Hansen",
    team: "Oslo",
  },
  sla: {
    deadline: "09:30",
    remainingMinutes: -38,
    state: "overdue",
  },
  nextAction: {
    kind: "approve_measurement",
    title: "Patikrinti R4 matavimą",
    reason:
      "Matavimo patikimumas yra 82 %. Prieš pasiūlymą reikia patvirtinti du stogo kraštus.",
    label: "Peržiūrėti R4",
    href: fixtureRfRoute,
    processStage: "evidence",
    requiredCapability: "measurement.review_approve",
    reviewMode: "review_and_commit",
    interaction: { mode: "executable", activation: "open_workbench" },
  },
  stages: [
    { id: "inquiry", state: "complete" },
    { id: "evidence", state: "current" },
    { id: "commercial", state: "blocked" },
    { id: "agreement", state: "upcoming" },
    { id: "work", state: "upcoming" },
    { id: "completion", state: "upcoming" },
  ],
  customerRecord: {
    questions: {
      total: 1,
      unresolved: true,
      active: {
        id: "message-104203",
        subject: "Re: Tilbud på takfornyelse",
        bodyText:
          "Takk. Kan dere sende tilbudet i dag, og bekrefte at stillas er inkludert?",
        channel: "email",
        receivedAt: "2026-09-03T15:06:00.000Z",
        documentReferences: ["T-1042-V1", "K-1042-V1"],
        replyStage: "prepare",
        fallbackHref: "/admin-v2/cases/1042",
      },
    },
    communications: [
      {
        id: "message-104203",
        direction: "inbound",
        channel: "email",
        category: "customer_question",
        status: "received",
        subject: "Re: Tilbud på takfornyelse",
        bodyText:
          "Takk. Kan dere sende tilbudet i dag, og bekrefte at stillas er inkludert?",
        at: "2026-09-03T15:06:00.000Z",
        replyToMessageId: 104202,
        attachments: [],
        fallbackHref: "/admin-v2/cases/1042#message-104203",
      },
      {
        id: "message-104202",
        direction: "outbound",
        channel: "email",
        category: "quote",
        status: "delivered",
        subject: "Tilbud på takfornyelse",
        bodyText:
          "Hei Kari. Vi har mottatt forespørselen og forbereder tilbud og avtalegrunnlag.",
        at: "2026-09-03T14:58:00.000Z",
        sentAt: "2026-09-03T14:57:00.000Z",
        deliveredAt: "2026-09-03T14:58:00.000Z",
        delivery: {
          approvedAt: "2026-09-03T14:56:00.000Z",
          queuedAt: "2026-09-03T14:56:30.000Z",
          recipient: "kari.nilsen@example.no",
          provider: "Resend",
        },
        attachments: [
          {
            id: "document-104201",
            filename: "tilbud-T-1042-V1.pdf",
            href: "/api/admin/media/104201",
          },
          {
            id: "document-104202",
            filename: "kontrakt-K-1042-V1.pdf",
            href: "/api/admin/media/104202",
          },
        ],
        fallbackHref: "/admin-v2/cases/1042#message-104202",
      },
    ],
    communicationPage: {
      totalCount: 27,
      remainingCount: 25,
      nextCursor: "mtlngbeo.28ei",
      loadMoreHref: "/api/admin-next/cases/1042/communications",
    },
    commercialVersions: [
      {
        id: "contract-104201",
        kind: "contract",
        reference: "K-1042-V1",
        version: 1,
        status: "draft",
        role: "working",
        createdAt: "2026-09-03T15:12:00.000Z",
        documentHash: "sha256:demo-contract-1042-v1",
        pdfHref: "/api/admin/quotes/104201/pdf",
        fallbackHref: "/admin-v2/cases/1042",
      },
      {
        id: "quote-104201",
        kind: "quote",
        reference: "T-1042-V1",
        version: 1,
        status: "draft",
        role: "working",
        createdAt: "2026-09-03T15:10:00.000Z",
        documentHash: "sha256:demo-quote-1042-v1",
        pdfHref: "/api/admin/quotes/104201/pdf",
        fallbackHref: "/admin-v2/cases/1042",
      },
    ],
    documents: [
      {
        id: "document-104201",
        filename: "tilbud-T-1042-V1.pdf",
        classification: "quote",
        mimeType: "application/pdf",
        createdAt: "2026-09-03T15:10:00.000Z",
        ownerType: "quote",
        ownerId: "104201",
        href: "/api/admin/media/104201",
      },
      {
        id: "document-104202",
        filename: "kontrakt-K-1042-V1.pdf",
        classification: "contract",
        mimeType: "application/pdf",
        createdAt: "2026-09-03T15:12:00.000Z",
        ownerType: "contract",
        ownerId: "104201",
        href: "/api/admin/media/104202",
      },
    ],
    history: [
      {
        id: "message-104203-received",
        kind: "message",
        title: "Kundespørsmål mottatt",
        status: "received",
        at: "2026-09-03T15:06:00.000Z",
        href: "/admin-v2/cases/1042#message-104203",
      },
      {
        id: "message-104202-delivered",
        kind: "message",
        title: "E-post levert til kunden",
        status: "delivered",
        at: "2026-09-03T14:58:00.000Z",
        href: "/admin-v2/cases/1042#message-104202",
      },
      {
        id: "lead-1042-created",
        kind: "lead",
        title: "Forespørsel mottatt",
        status: "new",
        at: "2026-09-03T14:48:00.000Z",
        href: "/admin-v2/cases/1042",
      },
    ],
  },
  evidence: [
    {
      id: "R4-2026-1042",
      kind: "measurement",
      state: "review",
      title: "R4 stogo matavimas",
      summary: "7 plokštumos · 2 kraštai pažymėti peržiūrai",
      metric: "186,4 m² · 82 %",
      recordedAt: "08:41",
      fallbackHref: "/admin-v2/cases",
      previewHref: fixtureRfRoute,
      previewAction: "review_measurement",
    },
    {
      id: "PHOTOSET-1042-01",
      kind: "photo",
      state: "verified",
      title: "Objekto nuotraukos",
      summary: "12 nuotraukų · adresas ir laikas patvirtinti",
      metric: "12 failų",
      recordedAt: "08:37",
      fallbackHref: "/admin-v2/cases",
    },
    {
      id: "DOC-1042-CONSENT",
      kind: "document",
      state: "verified",
      title: "Kliento sutikimas",
      summary: "Pasirašyta skaitmeniniu būdu",
      metric: "PDF · 214 KB",
      recordedAt: "Vakar 16:52",
      fallbackHref: "/admin-v2/documents",
      previewHref: "/admin-next-preview/cases/TF-1042/documents/preflight",
      previewAction: "document_preflight",
    },
    {
      id: "MSG-1042-03",
      kind: "communication",
      state: "verified",
      title: "Paskutinis kliento atsakymas",
      summary: "Klientas patvirtino, kad pasiūlymo laukia šiandien",
      recordedAt: "Vakar 17:06",
      fallbackHref: "/admin-v2/cases",
    },
  ],
  measurementReview: {
    reference: "R4-2026-1042",
    state: "review_required",
    horizontalAreaSquareMeters: 170.2,
    surfaceAreaSquareMeters: 190.8,
    areaSquareMeters: 186.4,
    overallPitchDegrees: 22,
    perimeterMeters: 61.2,
    confidencePercent: 82,
    planeCount: 7,
    comparedToReference: "R3",
    provenance: {
      evidenceId: "EVD-R4-1042-01",
      source: "Deterministic Preview fixture · R4 aerial evidence",
      capturedAt: "2026-09-01 08:37",
      modelVersion: "R4 preview schema v1",
      checksum: "sha256:demo-1042-r4",
    },
    planes: [
      { id: "P1", areaSquareMeters: 42.8, pitchDegrees: 22, state: "verified" },
      { id: "P2", areaSquareMeters: 38.6, pitchDegrees: 24, state: "verified" },
      { id: "P3", areaSquareMeters: 31.2, pitchDegrees: 22, state: "review" },
      { id: "P4", areaSquareMeters: 28.4, pitchDegrees: 24, state: "verified" },
      { id: "P5", areaSquareMeters: 18.7, pitchDegrees: 17, state: "verified" },
      { id: "P6", areaSquareMeters: 15.9, pitchDegrees: 17, state: "review" },
      { id: "P7", areaSquareMeters: 10.8, pitchDegrees: 12, state: "verified" },
    ],
    reviewEdges: [
      {
        id: "E-04",
        between: "P2 ↔ P3",
        reason: "Kraigo pabaigos taškas nesutampa su nuotraukos kontūru",
        varianceMeters: 0.42,
      },
      {
        id: "E-11",
        between: "P5 ↔ P6",
        reason: "Kraštą dalinai uždengia kamino šešėlis",
        varianceMeters: 0.31,
      },
    ],
    primarySlopes: [
      {
        id: "S1",
        areaSquareMeters: 54.2,
        pitchDegrees: 22,
        perimeterMeters: 31.8,
      },
      {
        id: "S2",
        areaSquareMeters: 49.8,
        pitchDegrees: 24,
        perimeterMeters: 29.6,
      },
      {
        id: "S3",
        areaSquareMeters: 43.6,
        pitchDegrees: 22,
        perimeterMeters: 27.4,
      },
      {
        id: "S4",
        areaSquareMeters: 38.8,
        pitchDegrees: 17,
        perimeterMeters: 25.9,
      },
    ],
    photos: [
      {
        id: "IMG-1042-N",
        label: "Šiaurinė stogo pusė",
        source: "Aerial source A",
        capturedAt: "2026-09-01 08:35",
      },
      {
        id: "IMG-1042-S",
        label: "Pietinė stogo pusė",
        source: "Aerial source B",
        capturedAt: "2026-09-01 08:36",
      },
      {
        id: "IMG-1042-C",
        label: "Kamino ir kraigo zona",
        source: "Field photo 07",
        capturedAt: "2026-09-01 08:37",
      },
    ],
    deltaFromR3: {
      areaSquareMeters: 3.8,
      confidencePoints: 6,
      planeCount: 1,
    },
    verificationGates: [
      {
        id: "source_identity",
        state: "verified",
        detail: "Evidence ID ir checksum sutampa",
      },
      { id: "plane_sum", state: "verified", detail: "S1–S4 suma yra 186,4 m²" },
      {
        id: "review_edges",
        state: "review_required",
        detail: "E-04 ir E-11 dar nepatvirtinti",
      },
      {
        id: "approval",
        state: "locked",
        detail: "Confirm laukia exact edge review",
      },
    ],
    nextAction:
      "Palyginti E-04 ir E-11 kraštus su objekto nuotraukomis, tada patvirtinti arba pataisyti geometriją veikiančiame matavimo sraute.",
    fallbackHref: "/admin-v2/cases",
  },
  documentPreflight: {
    packageReference: "PKG-1042-R12",
    state: "blocked",
    policyCode: "PS-SEND-007",
    recipient: {
      name: "Kari Nilsen",
      email: "kari.nilsen@example.no",
    },
    artifacts: [
      {
        id: "measurement",
        state: "review_required",
        reference: "R4-2026-1042",
        revision: "R4-r07",
        hash: "sha256:demo-r4-1042-r07",
        summary: "186,4 m² · 82 % · E-04 ir E-11 nepatvirtinti",
      },
      {
        id: "price",
        state: "locked",
        reference: "PRICE-1042-R12",
        revision: "price-r12",
        hash: "sha256:demo-price-1042-r12",
        summary: "NOK 286 400 su PVM · sutampa su pasiūlymu",
      },
      {
        id: "quote",
        state: "locked",
        reference: "Q-1042-R12",
        revision: "quote-r12",
        hash: "sha256:demo-quote-1042-r12",
        summary: "Pasiūlymo turinys sugeneruotas iš price-r12",
      },
      {
        id: "contract",
        state: "locked",
        reference: "C-1042-DRAFT-R03",
        revision: "contract-r03",
        hash: "sha256:demo-contract-1042-r03",
        summary: "Sutarties projektas susietas su Q-1042-R12",
      },
      {
        id: "recipient",
        state: "verified",
        reference: "RECIPIENT-1042-R02",
        revision: "recipient-r02",
        hash: "sha256:demo-recipient-1042-r02",
        summary: "Kari Nilsen · kari.nilsen@example.no",
      },
      {
        id: "pdf",
        state: "locked",
        reference: "PDF-1042-R12",
        revision: "pdf-r12",
        hash: "sha256:demo-pdf-1042-r12",
        summary: "8 puslapiai · PDF/A · sugeneruota iš exact artefaktų",
      },
    ],
    sequence: [
      { id: "measurement_review", state: "current" },
      { id: "reload", state: "locked" },
      { id: "verify_artifacts", state: "locked" },
      { id: "owner_gate", state: "locked" },
      { id: "send", state: "locked" },
    ],
    blocker:
      "R4-2026-1042 vis dar yra review_required: E-04 ir E-11 kraštai nepatvirtinti.",
    nextAction:
      "Atskirai atidaryti exact R4-r07 matavimą, patikrinti E-04 ir E-11, patvirtinti arba pataisyti geometriją veikiančiame sraute ir tik tada iš naujo įkelti preflight.",
    fallbackHref: "/admin-v2/documents",
  },
  timeline: [
    {
      id: "timeline-measurement-ready",
      kind: "measurement",
      title: "R4 matavimas paruoštas peržiūrai",
      summary: "Automatinė patikra pažymėjo du neaiškius kraštus.",
      at: "08:41",
      actor: "Matavimo variklis",
    },
    {
      id: "timeline-owner-assigned",
      kind: "assignment",
      title: "Byla priskirta atsakingam darbuotojui",
      summary: "Atsakomybė ir šiandienos terminas patvirtinti.",
      at: "08:05",
      actor: "Darbo eilė",
    },
    {
      id: "timeline-customer-reply",
      kind: "message",
      title: "Gautas kliento atsakymas",
      summary: "Klientas paprašė pasiūlymą atsiųsti šiandien.",
      at: "Vakar 17:06",
      actor: "Kari Nilsen",
    },
    {
      id: "timeline-case-created",
      kind: "automation",
      title: "Byla sukurta automatiškai",
      summary: "Užklausa patikrinta ir įtraukta į Oslo komandą.",
      at: "Vakar 16:48",
      actor: "Takfornyelse CRM",
    },
  ],
  timelineState: { status: "ready", source: "fixture" },
  fallback: {
    caseHref: "/admin-v2/cases",
    documentsHref: "/admin-v2/documents",
    workHref: "/admin-v2/work",
  },
};

export const adminNextFixtureCaseWorkspaceAdapter: AdminNextCaseWorkspaceAdapter =
  {
    async load(reference) {
      if (reference !== adminNextCaseWorkspaceFixture.reference) {
        return { status: "not_found" };
      }
      return {
        status: "ready",
        source: "fixture",
        value: adminNextCaseWorkspaceFixture,
      };
    },
  };
