import { NextResponse } from "next/server";
import { z } from "zod";
import { createPayloadAuditWriter } from "@/lib/audit/payload-audit-writer";
import { recordAuditEvent } from "@/lib/audit/audit-event";
import { correlationIdFromHeaders } from "@/lib/observability/correlation-id";
import { getPayload } from "@/lib/payload";
import {
  PayloadNorgeIBilderFinalImageStore,
  UpstashNorgeIBilderCaptureLedger,
} from "@/lib/providers/norge-i-bilder-payload-adapter";
import {
  NorgeIBilderCaptureError,
  NorgeIBilderCaptureProvider,
} from "@/lib/providers/norge-i-bilder-capture-provider";
import { verifiedLeadAddressCandidate } from "@/lib/leads/address-verification";
import { NorgeIBilderInteractiveUrlBuilder } from "@/lib/providers/norge-i-bilder-interactive-url";
import { NorgeIBilderVercelBrowserRuntime } from "@/lib/providers/norge-i-bilder-vercel-browser";
import { evaluateMutationOrigin } from "@/lib/security/request-origin";
import { userIsAdmin } from "@/payload/access/roles";

// This endpoint is deliberately scoped to the Roof Fusion preview workflow.
export const runtime = "nodejs";
export const maxDuration = 90;

const requestSchema = z.object({
  // A lead is the canonical case record in this application. Checking it
  // server-side prevents arbitrary address/coordinate collection requests.
  leadId: z.number().int().positive(),
  // Generated by the same-origin click handler. A transport retry must reuse
  // it; a new employee click creates a new UUID.
  clickId: z.string().uuid(),
  viewport: z
    .object({
      width: z.number().int().min(320).max(3840),
      height: z.number().int().min(240).max(2160),
    })
    .default({ width: 1920, height: 1080 }),
});

export async function POST(request: Request) {
  const correlationId = correlationIdFromHeaders(request.headers);
  const origin = evaluateMutationOrigin(request);
  if (!origin.allowed)
    return NextResponse.json(
      { error: "Invalid request origin" },
      { status: 403 },
    );

  const payload = await getPayload();
  const { user } = await payload.auth({ headers: request.headers });
  if (!user)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (!userIsAdmin(user))
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const parsed = requestSchema.safeParse(await request.json());
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid Norge i bilder capture request" },
      { status: 400 },
    );
  }

  const lead = await payload
    .findByID({
      collection: "leads",
      id: parsed.data.leadId,
      depth: 0,
      overrideAccess: true,
    })
    .catch(() => null);
  if (!lead)
    return NextResponse.json({ error: "Case not found" }, { status: 404 });
  const caseId = `lead-${lead.id}`;
  const address = verifiedLeadAddressCandidate(lead);
  if (!address) {
    return NextResponse.json(
      {
        error: "Case address must be server-verified",
        code: "ADDRESS_UNVERIFIED",
      },
      { status: 409 },
    );
  }

  try {
    const result = await new NorgeIBilderCaptureProvider({
      urlBuilder: new NorgeIBilderInteractiveUrlBuilder(),
      browser: new NorgeIBilderVercelBrowserRuntime(),
      ledger: new UpstashNorgeIBilderCaptureLedger(),
      store: new PayloadNorgeIBilderFinalImageStore(payload),
    }).capture({
      caseId,
      employeeId: String(user.id),
      clickId: parsed.data.clickId,
      // This must be assigned on the server, not trusted from a browser body.
      triggeredAt: new Date().toISOString(),
      target: {
        latitude: address.latitude,
        longitude: address.longitude,
        addressLabel: address.label,
      },
      viewport: parsed.data.viewport,
    });

    await recordAuditEvent(createPayloadAuditWriter(payload), {
      actorId: user.id,
      action: "norge-i-bilder.captured",
      entityType: "case",
      entityId: caseId,
      correlationId,
      changedFields: ["mapImage"],
      metadata: {
        attempts: result.attempts,
        source: result.source,
        sourceId: `norge-i-bilder:${result.mediaId}`,
        rawContentHash: result.rawContentHash,
        attribution: result.attribution,
        capturedAt: result.capturedAt,
        geoReferenceCrs: result.geoReference?.crs ?? null,
        geoReferenceTrust: result.geoReference?.extentTrust ?? null,
        geoReferenceBounds: result.geoReference
          ? JSON.stringify(result.geoReference.bounds)
          : null,
        imageWidth: result.geoReference?.imageWidth ?? null,
        imageHeight: result.geoReference?.imageHeight ?? null,
        trainingProhibited: true,
      },
    });
    return NextResponse.json(
      {
        mediaId: result.mediaId,
        evidenceId: result.mediaId,
        imageUrl: `/api/admin/media/${encodeURIComponent(result.mediaId)}`,
        source: result.source,
        sourceId: `norge-i-bilder:${result.mediaId}`,
        rawContentHash: result.rawContentHash,
        capturedAt: result.capturedAt,
        address,
        addressLabel: address.label,
        attribution: result.attribution,
        attempts: result.attempts,
        geoReference: result.geoReference,
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("Norge i bilder capture failed", {
      correlationId,
      code:
        error instanceof NorgeIBilderCaptureError ? error.code : "UNEXPECTED",
      message: error instanceof Error ? error.message : "Unknown capture error",
    });
    if (error instanceof NorgeIBilderCaptureError) {
      const status =
        error.code === "POLICY_DENIED"
          ? 429
          : error.code === "INVALID_REQUEST" ||
              error.code === "UNTRUSTED_SOURCE_URL"
            ? 400
            : 502;
      return NextResponse.json(
        { error: error.message, code: error.code },
        { status },
      );
    }
    const unavailable =
      error instanceof Error &&
      /(?:not configured|durable Upstash|Chromium pack)/i.test(error.message);
    return NextResponse.json(
      {
        error: unavailable
          ? "Norge i bilder capture is not configured"
          : "Norge i bilder capture failed",
        correlationId,
      },
      { status: unavailable ? 503 : 500 },
    );
  }
}
