"use client";

import { useState } from "react";
import { AdminAsyncFeedback } from "./admin-async-feedback";
import { BlockerSummary, DueIndicator, OwnerChip, StatusBadge, SyncState, VersionBadge } from "./admin-status-primitives";
import { ReviewAndCommit } from "./review-and-commit";

export function AdminSystemCatalog() {
  const [reviewOpen, setReviewOpen] = useState(false);
  const [commitState, setCommitState] = useState<"idle" | "pending" | "success">("idle");

  return (
    <div className="mx-auto max-w-6xl space-y-8" data-admin-next-section="system">
      <header><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--an-action)]">F1 · bendras kontraktas</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Administravimo komponentų katalogas</h1><p className="mt-2 max-w-3xl text-[var(--an-text-muted)]">Izoliuoti sintetiniai pavyzdžiai. Šis paviršius nekeičia domeno duomenų ir nėra kanoninis Production modulis.</p></header>
      <section className="rounded-2xl border border-[var(--an-border)] bg-[var(--an-surface-base)] p-5" aria-labelledby="catalog-semantics"><h2 className="text-xl font-bold" id="catalog-semantics">Būsena, atsakomybė ir versija</h2><div className="mt-4 flex flex-wrap items-center gap-3"><StatusBadge kind="active" /><StatusBadge kind="waiting" /><StatusBadge kind="blocked" /><StatusBadge kind="resolved" /><StatusBadge kind="draft" /><StatusBadge kind="superseded" /><OwnerChip name="Ola Nordmann" /><OwnerChip unassigned /><DueIndicator label="šiandien 14:00" /><DueIndicator label="vakar 16:00" overdue /><VersionBadge version="v4" /><VersionBadge current={false} version="v3" /><SyncState kind="synced" /><SyncState kind="pending" /></div><div className="mt-4"><BlockerSummary recovery={<button className="min-h-11 rounded-xl border border-[var(--an-danger)] px-3 font-bold text-[var(--an-danger)]" type="button">Paprašyti trūkstamos nuotraukos</button>}>Trūksta privalomos šiaurinio šlaito nuotraukos.</BlockerSummary></div></section>
      <section className="rounded-2xl border border-[var(--an-border)] bg-[var(--an-surface-base)] p-5" aria-labelledby="catalog-async"><h2 className="text-xl font-bold" id="catalog-async">Asinchroninis grįžtamasis ryšys</h2><div className="mt-4 grid gap-3 lg:grid-cols-2"><AdminAsyncFeedback action="Tikrinamas matavimo hash" state="pending" /><AdminAsyncFeedback action="Pasiūlymo juodraštis" state="success" /><AdminAsyncFeedback action="Nuotraukos įkėlimas" state="offline" /><AdminAsyncFeedback action="Dokumentų paketas" correlationId="syn-demo-004" message="Nepavyko patikrinti gavėjo" retryIsSafe state="error" /></div></section>
      <section className="rounded-2xl border border-[var(--an-border)] bg-[var(--an-surface-base)] p-5" aria-labelledby="catalog-review"><h2 className="text-xl font-bold" id="catalog-review">Review / commit</h2><p className="mt-2 text-sm text-[var(--an-text-muted)]">Materialus veiksmas rodo automatinę patikrą, konkrečią pasekmę ir tai, ko komanda neatliks.</p><button className="mt-4 min-h-11 rounded-xl bg-[var(--an-action)] px-4 font-black text-[var(--an-action-ink)]" onClick={() => setReviewOpen(true)} type="button">Atverti tikslų preflight</button></section>
      <ReviewAndCommit acknowledgement="Patvirtinu, kad gavėjas ir pasiūlymo v4 versija yra teisingi." changes={["Bus suformuotas vienas pasiūlymo v4 PDF paketas.", "Paketas bus įrašytas kaip paruoštas siųsti."]} commitLabel="Paruošti paketą" description="Patikrinkite gavėją, versiją ir automatinio preflight rezultatą." idempotencyKey="catalog-package-case-1042-v4" onCommit={async () => { setCommitState("pending"); await new Promise((resolve) => window.setTimeout(resolve, 400)); setCommitState("success"); }} onOpenChange={(next) => { setReviewOpen(next); if (!next) setCommitState("idle"); }} open={reviewOpen} postCommitState="Pasiūlymo paketas paruoštas, bet neišsiųstas" preflight={[{ id: "recipient", label: "Gavėjas", detail: "kunde@example.invalid · patvirtintas bylos kontaktas", state: "pass" }, { id: "version", label: "Versija", detail: "Pasiūlymas v4 · dabartinė patvirtinta versija", state: "pass" }, { id: "delivery", label: "Siuntimas", detail: "Ši komanda nieko nesiunčia", state: "warning" }]} risk="material" state={commitState} title="Paruošti pasiūlymo paketą" untouched={["El. laiškas nebus išsiųstas.", "Matavimo ir kainos versijos nebus pakeistos."]} />
    </div>
  );
}
